
#include "../../BumpToRoughness.osl"

shader BumpToRoughnessTestShader(
    vector coordinates = vector(0, 0, 0),

    float inputNoise = 0,
    normal inputNormal = normal(0, 0, 1),
    int isTangentSpace = 1,
    float baseRoughness = 0.001,
    float gain = 1.0,
    float anisotropyGain = 1.0,
    
    output closure color Cout = 0,
    output normal outNormal = normal(0, 0, 1)
) {
    float noiseTest = noise("perlin", coordinates);

    point Pbump = P + normalize(Ng) * noiseTest;
    //normal inputNormal = normalize(calculatenormal(Pbump));

    normal bumpNormal;
    float roughness;
    float anisotropy;
    vector anisotropyDirection;
    float roughnessV;
    float roughnessU;

    BumpToRoughness(    
        coordinates, //vector UV,
        inputNormal, //vector bumpNormal,
        
        isTangentSpace, //int isTangentSpace,
        baseRoughness, //float baseRoughness,
        gain, //float gain,
        anisotropyGain, //float anisotropyGain,
        
        // Outputs
        bumpNormal,
        roughness,
        anisotropy,
        anisotropyDirection,
        roughnessV,
        roughnessU
    );

    closure color base = oren_nayar_diffuse_bsdf(Ng, color(0.05), roughness);

    closure color specular = generalized_schlick_bsdf(
        bumpNormal, anisotropyDirection,// normal N, vector U, 
        color(1.0), // color reflection_tint, 
        color(0), // color transmission_tint, 
        roughnessV, // float roughness_x, 
        roughnessU, // float roughness_y, 
        color(0.04,0.04,0.04), // f0
        color(1,1,1), // f90
        5, // float exponent, 
        "ggx"
    );

    Cout = base;
    Cout = layer(specular, base);


    outNormal = bumpNormal;

}