// AutolibScratch

shader AutolibScratch [[ 
    string category = "autolib" 
]] (
    vector UV = vector(u, v, 0),
    float Density = 0.1 [[ float min = 0, int interactive = 1 ]],
    float Width = 0.001 [[ float min = 0, int interactive = 1 ]],
    float NormalStrength = 1.0 [[ float min = 0, int interactive = 1 ]],
    output normal Normal = N,
    output float Height = 0.0,
    output float Alpha = 0.0
) {

    float delta = 1.0/(40 - 1);
    float maxRadius = sqrt(Density);
    int maxSearchCell = (int)ceil(maxRadius/delta);
    point index = point(round(UV.x/delta), round(UV.y/delta), 0.0);

    int found = 0;
    for (int x = -maxSearchCell; x <= maxSearchCell && !found; ++x){
        for (int y = -maxSearchCell; y <= maxSearchCell && !found; ++y){
            point currentIndex = index + point(x, y, 0);
            point currentOrigin = (currentIndex + (hashnoise(currentIndex) - 0.5)) * delta;

            float directionValue = hashnoise(currentIndex + vector(123, 456, 0));
            
            float theta = directionValue * M_PI;

            vector bitangent = vector(-sin(theta), cos(theta), 0);
            
            vector diff = UV - currentOrigin;
            float dist = dot(diff, bitangent);
            float actualWidth = Width * hashnoise(currentIndex);

            if (abs(dist) < actualWidth * 0.5) {
                float t = dist / (actualWidth * 0.5);

                Normal = normalize(normal(0,0,1) - bitangent * t * NormalStrength);
                Alpha = 1.0;
                Height = 1.0 - (t * t); // smooth parabolic dip across scratch Width
                found = 1;
            }
        }
    }
}