// AutolibNoisyVoronoi

point fract(point p) {
    point fractional = point(0);
    float whole_x= floor(p[0]);
    float whole_y = floor(p[1]);
    float whole_z = floor(p[2]);
    fractional[0] = p[0] - whole_x;
    fractional[1] = p[1] - whole_y;
    fractional[2] = p[2] - whole_z;
    return fractional;
}

#define CELL 0
#define HASH 1
#define SIMPLEX 2

shader AutolibNoisyVoronoi [[ 
    string category = "autolib" 
]] (
    // Input Mapping
    point UVW = transform("world", P) [[ string help = "World Space UVW" ]],
    int ObjectUVW = 1 [[ string help = "Use Object Space UVW instead of World Space UVW", int min = 0, int max = 1 ]],

    // Color 
    color Color1 = 1,
    color Color2 = 0,
    int Multicolored = 0 [[ string help = "Output random colors. Color 1 and Color 2 are ignored.", int min = 0, int max = 1 ]],

    float Scale = 1 [[ string help = "Size of the cell pattern", float min = 0.001, float max = 10 ]],
    float scaleMultiplier = 1 [[ string help = "Multiplier for finer control of pattern size", float min = 0.001, float max = 10 ]],

    int seed = 0 [[ string help = "Seed for random cell pattern", int min = 1, int max = 32767 ]],
    float offsetMultiplier = 6 [[ string help = "Multiplier for the offset for pattern variations", string page = "Extra control", float min = 0.01, float max = 10 ]],
    int blobby = 0 [[ string help = "Turns on or off metaball behavior", int min = 0, int max = 1 ]],
    float cellExpansion = 1.5 [[ string help = "Fill of each cell", float min = -2, float max = 2 ]],

    // Noise 
    float noiseScale = 1 [[ string help = "Edge noise size", float min = 0, float max = 10  ]],
    float noiseAmount = 0.15 [[ string help = "Multiplier for the edge noise size", float min = 0, float max = 10  ]],
    int octaves = 1 [[ string help = "Number of noise iterations", int min = 1, int max = 20 ]],
    int noiseType = SIMPLEX [[ string help = "Noise type", string widget = "mapper", string options = "cell|hash|simplex" ]],

    output color Color = 0
) {
    point uvw = point(0);

    if (ObjectUVW == 1) {
        uvw = transform("object", P) / (Scale * scaleMultiplier); // object space uvw
    } else {
        uvw = UVW / (Scale * scaleMultiplier); // world space uvw
    }
    
    uvw += 0.0001; // prevents z-fighting on objects with no depth

    point intUVW= floor(uvw);	
    point fracUVW = fract(uvw);
    float minDistance = 1.5; 
    point minPoint = 0;     
    float positionNoise = 0;

    // noise iterations
    if (noiseScale > 0 && noiseAmount > 0){
        for (int o = 1; o < octaves + 1; o++) {
            float n = noiseScale / (o * 4); // reduce noise size by 4 each iteration
            int shift = o; // prevents spiky striations from the origin
            if (noiseType == CELL) {
                positionNoise += noise("cell", point((uvw[0] + shift) / n, (uvw[1] + shift) / n, (uvw[2] + shift )/ n)) * noiseAmount;
            } else if (noiseType == HASH) {
                positionNoise += noise("hash", point((uvw[0] + shift) / n, (uvw[1] + shift) / n, (uvw[2] + shift )/ n)) * noiseAmount;
            } else {
                positionNoise += noise("simplex", point((uvw[0] + shift) / n, (uvw[1] + shift) / n, (uvw[2] + shift )/ n)) * noiseAmount;
             }
        }
    }

    // Voronoi cells 
    for (int x = -1; x <= 1; x++) {
        for (int y = -1; y <= 1; y++) {
            for (int z = -1; z <= 1; z++) {
                point neighbor = point(float(x), float(y), float(z));

                point offset = fract(hashnoise(intUVW + neighbor, 1) * seed);
    
                offset = 0.5 + 0.5 * sin(offsetMultiplier * offset);
    
                // Position of the cell with added noise
                point newPoint = neighbor + offset - fracUVW + positionNoise;
                float cellDistance = length(newPoint);
                
                if(cellDistance < minDistance) {
                    minDistance = cellDistance;
                    minPoint = offset;
                }
                
               // blend circles
                if (blobby == 1) {
                    minDistance = min(minDistance, minDistance * cellDistance);
                }
            }
        }
    }
    
    // greyscale values of the cells
    float cellValue = max(dot(minPoint, point(0.25,0.5,0.0)), step(cellExpansion + positionNoise, minDistance)) ;

    if (Multicolored == 1) {
        Color = color( max(dot(minPoint, point(1,0,0)), step(cellExpansion + positionNoise, minDistance)),
                          max(dot(minPoint, point(0,1,0)), step(cellExpansion + positionNoise, minDistance)),
                          max(dot(minPoint, point(0,0,1)), step(cellExpansion + positionNoise, minDistance)) );
    } else {
      Color = mix(Color1, Color2, cellValue); 
    }
}