
#ifdef ENTRY_SEE_THROUGH
    #define  DEFAULT_SEE_THROUGH(x) = x
#else
    #define  DEFAULT_SEE_THROUGH(x)
#endif

#ifndef ENTRY_SEE_THROUGH
	#define ENTRY_SEE_THROUGH void
#endif

ENTRY_SEE_THROUGH Toon(
    color outlineColor = color(0,0,0),
    float outlineWidth = 0.1,
    output color outColor = 1,
    float alpha = 0.5,
    float clearcoatRoughness = 1,
    float clearcoatIOR = 1,
    output closure color Cout = 0
)
{
    vector viewDir = normalize(I);
    
    float edgeFactor = 1.0 - dot(N, -viewDir);
    
    edgeFactor = smoothstep(outlineWidth * 0.5, outlineWidth, edgeFactor);
    
    outColor = mix(color(1,1,1), outlineColor, edgeFactor);


    normal dir = normal(0,0,1);

    closure color base = dielectric_bsdf(
		N, 0,
		color(0.5), // reflection_tint
		color(1.0), // transmission_tint
		clearcoatRoughness, // roughness_y
		clearcoatRoughness, // roughness_x
		clearcoatIOR, // IOR
		"ggx"
    );

    Cout = mix(transparent(), base, alpha);

}