#ifdef NO_ENTRY 
    #define ENTRY_METALLIC_PAINT void 
#endif

#ifndef ENTRY_METALLIC_PAINT
    #define  DEFAULT_METALLIC_PAINT(x) = x
	#define ENTRY_METALLIC_PAINT shader
#else
    #define  DEFAULT_METALLIC_PAINT(x)
#endif

vector ID(vector x, int flakeSeed) {
    vector n = floor(x);
    vector f = x-floor(x);
    vector m = vector(8);
    for( int k = -1; k <= 1; k++ ) {
		for( int j = -1; j <= 1; j++ ) {
			for( int i = -1; i <= 1; i++ ) {
				vector g = vector( float(i), float(j),float(k) );  	
				vector o = noise("hash",n + g,flakeSeed);
				vector r = g - f + (0.5 + (0.5 * sin(M_2PI * o)));
				float s = dot(r, r);      
				s < m.x ? m = vector(s, o.x, o.y) : 0;
			}
		}
	}  
	
    return vector( sqrt(m.x), m.y + m.z, m.y + m.x);
}

float IDs( output float x, int flakeSeed ) { 
	x = -1000 + x * 2000;
	x = int(trunc(x));	
	float xRatio = noise("cell", vector(abs(x), abs(flakeSeed), 11)); 
	
	return mix(0, 1, xRatio);
}	

void generateFlakes( point p, 
					 int flakeSeed,
					 float flakeDensity,
					 output float rehash,
					 output float outAlpha,
					 output normal outNormal ) 
{

	vector k = ID(p, flakeSeed);

    float angle = k.y * M_2PI;

    float x = 0.5 + 0.5 * cos(angle);
    float y = 0.5 + 0.5 * sin(angle);
    float z = 0.5 + 0.5 * tan(angle);

	outNormal = normalize(vector(x, y, z) * 2.0 - 1.0);
    outNormal = outNormal * 0.5 + 0.5;

	int flakeSeeds[3] = {4, 4, 1};

	for (int i = 0; i < 3; i++) {
		outNormal[i] = IDs(outNormal[i], flakeSeeds[i]);
	}

    outNormal.z = 0.5 + 0.5 * outNormal.z;

    float h = -1000.0 + outNormal.x * 2000.0;
    h = int(trunc(h));
    rehash = noise("cell", vector(abs(h), 16, 11));

	if (flakeDensity <= rehash) {
        outNormal = vector(0.5, 0.5, 1.0);
    }

	outAlpha = (outNormal.x != 0.5) ? 1.0 : 0.0;
}

float specNoise(point position, 
				float density, 
				float sharpness, 
				int octaves
) {
    float totalNoise = 0.0;
    float amplitude = 1.0;
    float frequency = 1.0;
    
    // Fractal noise with multiple octaves
    for (int i = 0; i < octaves; i++) {
        float cellNoise = noise("gabor", position * frequency);
        float speckle = smoothstep(0.1, 1.0 - density, cellNoise);
        totalNoise += amplitude * speckle;
        amplitude *= 0.75;
        frequency *= 2.0;
    }

    totalNoise = pow(totalNoise, 1.0 / max(sharpness, 0.01));

    float variation = noise("gabor", position * 0.5) * 0.2 + 0.8;

    return clamp(totalNoise * variation, 0.0, 1.0);
}

// Return alpha^2 parameter from normal divergence
 float bump_alpha2(normal Nbump) {
    float cos_d = min(abs(dot(Ng, Nbump)), 1.0);
    float tan2_d = (1 - cos_d * cos_d) / (cos_d * cos_d);
    return clamp(0.125 * tan2_d, 0.0, 1.0);
 }

 // Shadowing factor
float bump_shadowing_function(vector Ld, float alpha2) {
    float cos_i = max(abs(dot(Ng, Ld)), 1e-6);
    float tan2_i = (1 - cos_i * cos_i) / (cos_i * cos_i);
    return 2.0 / (1 + sqrt(1 + alpha2 * tan2_i));
}

ENTRY_METALLIC_PAINT MetallicPaintShader (
    vector UV  DEFAULT_METALLIC_PAINT(vector(u, v, 0)),
    int useUV  DEFAULT_METALLIC_PAINT(0) [[ string doc = "Defaults to P otherwise", string widget = "checkBox" ]],

	//Primer
	float primerWeight  DEFAULT_METALLIC_PAINT(1.0) [[ string uifolder = "Primer", float uimin = 0.0, float uimax = 1.0 ]],
	color primerColor  DEFAULT_METALLIC_PAINT(color(1.0, 0.1, 0.1)) [[ string uifolder = "Primer" ]],
	float primerRoughness  DEFAULT_METALLIC_PAINT(1.0) [[ string uifolder = "Primer", float uimin = 0.0, float uimax = 1.0 ]],
	
	//Flake Pattern
	int numMetallicLayers  DEFAULT_METALLIC_PAINT(6) [[ string uifolder = "Flake Pattern", string doc = "Number of intermediate/metallic layers between primer and clearcoat. Number of patties in a burger", int min = 1 ]],
	float flakeScale  DEFAULT_METALLIC_PAINT(0.001) [[ string uifolder = "Flake Pattern", float uimin = 0.0, float uimax = 200.0 ]],
	float flakeDensity  DEFAULT_METALLIC_PAINT(0.2) [[ string uifolder = "Flake Pattern", float uimin = 0.0, float uimax = 1.0 ]],
    float flakeRandomize  DEFAULT_METALLIC_PAINT(0.2) [[ string uifolder = "Flake Pattern", string doc = "Dictates the randomness of the flake orientations (normals)", float uimin = 0.0, float uimax = 1.0 ]],
	int flakeSeed  DEFAULT_METALLIC_PAINT(1) [[ string uifolder = "Flake Pattern", int min = 0, int max = 100 ]],

	//Flakes 
	float flakeWeight  DEFAULT_METALLIC_PAINT(1.0) [[ string uifolder = "Flakes", string doc = "Visibility of the metallic flakes", float uimin = 0.0, float uimax = 1.0 ]],
	color flakeReflectivity  DEFAULT_METALLIC_PAINT(color(0.95, 0.95, 0.95)) [[ string uifolder = "Flakes" ]],
	color flakeEdgeTint  DEFAULT_METALLIC_PAINT(color(1.0, 1.0, 1.0)) [[ string uifolder = "Flakes" ]],
	float flakeRoughness  DEFAULT_METALLIC_PAINT(0.1) [[ string uifolder = "Flakes", float uimin = 0.0, float uimax = 1.0 ]],
	//Base
	float baseWeight  DEFAULT_METALLIC_PAINT(1.0) [[ string uifolder = "Base", string doc = "Weight of the paint that is suspended in the same layer as the flakes", float uimin = 0.0, float uimax = 1.0 ]],
	color baseColor  DEFAULT_METALLIC_PAINT(color(1.0, 0.1, 0.1)) [[ string uifolder = "Base", string doc = "Flake Layer Color" ]],
	float baseRoughness  DEFAULT_METALLIC_PAINT(0.5) [[ string uifolder = "Base", float uimin = 0.0, float uimax = 1.0 ]],
	float baseIOR  DEFAULT_METALLIC_PAINT(1.9) [[ string uifolder = "Base", float uimin = 1.0, float uimax = 3.0 ]],

	//Clearcoat
	float clearcoatWeight  DEFAULT_METALLIC_PAINT(1.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatAnisotropy  DEFAULT_METALLIC_PAINT(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatRoughness  DEFAULT_METALLIC_PAINT(0.05) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatRotation  DEFAULT_METALLIC_PAINT(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatIOR  DEFAULT_METALLIC_PAINT(1.4) [[ string uifolder = "Clearcoat", float uimin = 1.0, float uimax = 3.0 ]],
	float clearcoatExponent  DEFAULT_METALLIC_PAINT(5) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 10.0 ]],

	output closure color Cout  DEFAULT_METALLIC_PAINT(0)
) {
    point pos = transform("object", useUV ? UV : P) / flakeScale;

	//Primer 
	closure color primerLayer = primerWeight * burley_diffuse_bsdf(N, primerColor, primerRoughness);

	//Metallic Flake and Base Layers
	closure color baseLayer = 0;


	//float shadowingFactor = 0.0;

	for (int i = 0; i < numMetallicLayers; i++) {
		
		float rehash;
		float outAlpha;
		normal outNormal;
		int seed = flakeSeed + i;

		generateFlakes(pos, seed, flakeDensity, rehash, outAlpha, outNormal);
		normal finalNormal = mix(Ng, outNormal, flakeRandomize);

		closure color addFlakes;
		if (outAlpha > 0.5) {
			color flakeIOR, flakeExtinction;
			artistic_ior(flakeReflectivity, flakeEdgeTint, flakeIOR, flakeExtinction);
			
			addFlakes = flakeWeight * conductor_bsdf(
				finalNormal, 0,
				flakeRoughness, // roughness_x 
				flakeRoughness, // roughness_y 
				flakeIOR, // ior 
				flakeExtinction, // extinction 
				"ggx"
			);
		} else {
			addFlakes = baseWeight * dielectric_bsdf(
				N, 0,
				baseColor, // reflection_tint,  
				0, // transmission_tint, 
				baseRoughness, // roughness_x, 
				baseRoughness, // roughness_y,  
				baseIOR, // ior 
				"ggx"
			);
		}

		if (i == 0) { // if first layer
			baseLayer = addFlakes;
		} else {	
			baseLayer = layer(addFlakes, baseLayer);
		}

	}

	closure color baseAndPrimerLayer = layer(baseLayer, primerLayer);

	vector T = vector(cos(2 * M_PI * clearcoatRotation), sin(2 * M_PI * clearcoatRotation), 0);

	//Clearcoat
	closure color clearcoatBase = generalized_schlick_bsdf(
		N, T,
		color(1.0), // reflection_tint
		color(0.0), // transmission_tint
		clearcoatRoughness, // roughness_y
		clearcoatRoughness * (1.0 - clearcoatAnisotropy), // roughness_x
		color(0.04), // f0
		color(1,1,1), // f90
		clearcoatExponent, // exponent
		"ggx" // distribution
	);

	closure color clearcoatTop = dielectric_bsdf(
		N, T,
		color(1.0), // reflection_tint
		color(0.0), // transmission_tint
		clearcoatRoughness, // roughness_y
		clearcoatRoughness * (1.0 - clearcoatAnisotropy), // roughness_x
		clearcoatIOR, // IOR
		"ggx"
	);

	closure color clearcoat = clearcoatWeight * layer(clearcoatTop, clearcoatBase);

	Cout = layer(clearcoat, baseAndPrimerLayer);
	
}
