#ifndef SOLO_SHADER   
    #define ENTRY_SPLATTER_PAINT void 
#endif

#ifndef ENTRY_SPLATTER_PAINT
    #define  DEFAULT_SPLATTER_PAINT(x) = x
	#define ENTRY_SPLATTER_PAINT surface
#else
    #define  DEFAULT_SPLATTER_PAINT(x)
#endif

ENTRY_SPLATTER_PAINT SplatterPaint [[ 
    string nodegroup = "autolib", 
]] (
    vector UV  DEFAULT_SPLATTER_PAINT(vector(u, v, 0)),

	//Primer
	float primerWeight  DEFAULT_SPLATTER_PAINT(1.0) [[ string uifolder = "Primer", float uimin = 0.0, float uimax = 1.0 ]],
	color primerColor  DEFAULT_SPLATTER_PAINT(color(1.0, 0.1, 0.1)) [[ string uifolder = "Primer" ]],
	float primerRoughness  DEFAULT_SPLATTER_PAINT(1.0) [[ string uifolder = "Primer", float uimin = 0.0, float uimax = 1.0 ]],

    // Splatter layers
    closure color splatterLayer1 DEFAULT_SPLATTER_PAINT(0),
    closure color splatterLayer2 DEFAULT_SPLATTER_PAINT(0),
    closure color splatterLayer3 DEFAULT_SPLATTER_PAINT(0),

	//Clearcoat
	float clearcoatWeight  DEFAULT_SPLATTER_PAINT(1.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatAnisotropy  DEFAULT_SPLATTER_PAINT(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatRoughness  DEFAULT_SPLATTER_PAINT(0.05) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatRotation  DEFAULT_SPLATTER_PAINT(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float clearcoatIOR  DEFAULT_SPLATTER_PAINT(1.4) [[ string uifolder = "Clearcoat", float uimin = 1.0, float uimax = 3.0 ]],
	float clearcoatExponent  DEFAULT_SPLATTER_PAINT(5) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 10.0 ]],

	output closure color Cout  DEFAULT_SPLATTER_PAINT(0)
) {
	//Primer 
	color finalPrimerColor = primerColor; // fallback

	//Metallic Flake and Base Layers
	closure color baseLayer = 0;
	float cumulativeHeight = 0.0;

    closure color splatterLayers[3] = { splatterLayer3, splatterLayer2, splatterLayer1 };
    int numPrimaryLayers = arraylength(splatterLayers);

	for (int i = 0; i < numPrimaryLayers; i++) {

        closure color splatterLayer = splatterLayers[i];

        if (i == 0) {
            baseLayer = splatterLayer;
        } else {
            baseLayer = layer(splatterLayer, baseLayer);
        }
	}

	closure color primerLayer = primerWeight * burley_diffuse_bsdf(Ng, finalPrimerColor, primerRoughness);
	closure color baseAndPrimerLayer = layer(baseLayer, primerLayer);

	vector T = vector(cos(2 * M_PI * clearcoatRotation), sin(2 * M_PI * clearcoatRotation), 0);

	//Clearcoat
	closure color clearcoatBase = generalized_schlick_bsdf(
		N, T,
		color(1.0), // reflection_tint
		color(0.0), // transmission_tint
		clearcoatRoughness, // roughness_y
		clearcoatRoughness * (1.0 - clearcoatAnisotropy), // roughness_x
		color(0.04), // f0
		color(1,1,1), // f90
		clearcoatExponent, // exponent
		"ggx" // distribution
	);

	closure color clearcoatTop = dielectric_bsdf(
		N, T,
		color(1.0), // reflection_tint
		color(0.0), // transmission_tint
		clearcoatRoughness, // roughness_y
		clearcoatRoughness * (1.0 - clearcoatAnisotropy), // roughness_x
		clearcoatIOR, // IOR
		"ggx"
	);

	closure color clearcoat = clearcoatWeight * layer(clearcoatTop, clearcoatBase);

	Cout = layer(clearcoat, baseAndPrimerLayer);
}