#define UV 0
#define PRIMVAR 1
#define POBJECT 2
#define PWORLD 3

shader AutolibManifold [[
    string category = "autolib"
]] (
    int CoordType = UV [[ string widget = "mapper", string options = "uv|primvar|PObject|PWorld" ]],
    string PrimvarName = "st" [[ string widget = "null", string help = "Name of the primvar to use if CoordType is set to primvar" ]],
    point OtherCoord = 0 [[ string widget = "null", string help = "Will only be used if connected"]],
    vector Scale = 1.0 [[ int interactive = 1 ]],
    vector Repeat = 1.0 [[ int interactive = 1 ]],
    vector Offset = 0.0 [[ int interactive = 1 ]],
    float Rotate = 0.0 [[ string units = "degrees", float min = 0, float max = 360 ]],

    output point Result = 0
) {
    point p;

    if (isconnected(OtherCoord)) {
        p = OtherCoord;
    } else if (CoordType == UV) {
        p = point(u, v, 0);
    } else if (CoordType == PRIMVAR) {
        getattribute(PrimvarName, p);
    } else if (CoordType == POBJECT) {
        p = transform("object", P);
    } else if (CoordType == PWORLD) {
        p = transform("world", P);
    } else {
        p = point(u, v, 0);
    }
    
    // Rotate
    if (Rotate != 0.0) {
        float angle = radians(Rotate);
        float s = sin(angle);
        float c = cos(angle);
        float x = p[0];
        float y = p[1];
        p[0] = x * c - y * s;
        p[1] = x * s + y * c;
    }

    // Scale and Offset
    if (Scale != 1.0) {
        p *= Scale;
    }
    if (Repeat != vector(1.0)) {
        p *= Repeat;
    }
    if (Offset != vector(0.0)) {
        p += Offset;
    }

    Result = p;
}