shader AutolibMix [[
    string category = "autolib"
]] (
    color ColorA = 0,
    color ColorB = 1,
    float Mixer = 0 [[ string widget = "number", int slider = 1, float slidermin = 0, float slidermax = 1 ]],
    int Clamp = 0 [[ string widget = "checkBox", int min = 0, int max = 1 ]],

    output color RGB = 0
) {
    float clampedMixer = Mixer;
    if (Clamp == 1) {
        clampedMixer = clamp(Mixer, 0.0, 1.0);
    }

    if (clampedMixer <= 0.0) {
        RGB = ColorA;
        return;
    } else if (clampedMixer >= 1.0) {
        RGB = ColorB;
        return;
    }

    RGB = mix(ColorA, ColorB, clampedMixer);
}