
#define CHANNEL_R 0
#define CHANNEL_G 1
#define CHANNEL_B 2
#define LUMINANCE 3
#define AVERAGE 4

shader AutolibColorToFloat [[
    string category = "autolib"
]] (
    color Input = 0.0 [[ string label = "Input", string help = "The color or vector to extract a float from." ]],
    int Mode = AVERAGE [[ string widget = "mapper",  string options = "ChannelR|ChannelG|ChannelB|Luminance|Average" ]],

    output float ResultF = 0
) {
    if (Mode == CHANNEL_R) {
        ResultF = Input.r;
    } else if (Mode == CHANNEL_G) {
        ResultF = Input.g;
    } else if (Mode == CHANNEL_B) {
        ResultF = Input.b;
    } else if (Mode == LUMINANCE) {
        ResultF = luminance(Input);
    } else if (Mode == AVERAGE) {
        ResultF = (Input.r + Input.g + Input.b) / 3.0;
    } else {
        ResultF = 0.5;
    }
}