#ifndef SOLO_SHADER   
    #define ENTRY_RYB void 
#endif

#ifndef ENTRY_RYB
    #define  DEFAULT_RYB(x) = x
    #define ENTRY_RYB shader
#else
    #define  DEFAULT_RYB(x)
#endif

float cubicInterpolate(float t, float A, float B) {
    float weight = pow(t, 2) * (3 - 2*t);
    return A + weight * (B - A);
}


// or 
ENTRY_RYB AutolibRYB [[
    string nodegroup = "autolib"
]] (
    float red DEFAULT_RYB(0.5) [[ float uimin = 0, float uimax = 1 ]],
    float yellow DEFAULT_RYB(0.5) [[ float uimin = 0, float uimax = 1 ]],
    float blue DEFAULT_RYB(0.5) [[ float uimin = 0, float uimax = 1 ]],
    int method DEFAULT_RYB(1) [[ string doc = "0 = Sugita, 1 = Gossett"]],
    output color Cout DEFAULT_RYB(1)
) {
    // https://bahamas10.github.io/ryb/assets/ryb.pdf
    if (method == 1) {
        vector corners[8] = {
            {1,     1,     1    }, // [0] R=0,Y=0,B=0 - white
            {1,     1,     0    }, // [1] R=0,Y=1,B=0 - yellow
            {1,     0,     0    }, // [2] R=1,Y=0,B=0 - red
            {1,     0.5,   0    }, // [3] R=1,Y=1,B=0 - orange
            {0.163, 0.373, 0.6  }, // [4] R=0,Y=0,B=1 - blue
            {0,     0.66,  0.2  }, // [5] R=0,Y=1,B=1 - green
            {0.5,   0,     0.5  }, // [6] R=1,Y=0,B=1 - purple
            {0.2,   0.094, 0    }  // [7] R=1,Y=1,B=1 - dark brown
        };

        color rgb;
        for (int i = 0; i < 3; i++) {
            float x0 = cubicInterpolate(blue, corners[0][i], corners[4][i]);
            float x1 = cubicInterpolate(blue, corners[1][i], corners[5][i]);
            float x2 = cubicInterpolate(blue, corners[2][i], corners[6][i]);
            float x3 = cubicInterpolate(blue, corners[3][i], corners[7][i]);
            float y0 = cubicInterpolate(yellow, x0, x1);
            float y1 = cubicInterpolate(yellow, x2, x3);
            rgb[i]   = cubicInterpolate(red, y0, y1);
        }
        Cout = rgb;
    }

    // https://history.siggraph.org/wp-content/uploads/2022/10/2015-Poster-83-Sugita_Paint-like-Compositing-Based-on-RYB-Color-Model.pdf
    if (method == 0) {
        // Eq 5
        float black = min(red, min(yellow, blue));
        float redNoBlack = red - black;
        float yellowNoBlack = yellow - black;
        float blueNoBlack = blue - black;

        // Eq 6
        float redRGB   = redNoBlack + yellowNoBlack - min(yellowNoBlack, blueNoBlack);
        float greenRGB = yellowNoBlack + 2.0 * min(yellowNoBlack, blueNoBlack);
        float blueRGB  = 2.0 * (blueNoBlack - min(yellowNoBlack, blueNoBlack));

        // Eq 7
        float maxRYB = max(redNoBlack, max(yellowNoBlack, blueNoBlack));
        float maxRGB = max(redRGB, max(greenRGB, blueRGB));
        float scale = (maxRYB > 0.0 && maxRGB > 0.0) ? maxRGB / maxRYB : 1.0;
        redRGB   /= scale;
        greenRGB /= scale;
        blueRGB  /= scale;

        // Eq 8
        float white = min(1.0 - redRGB, min(1.0 - greenRGB, 1.0 - blueRGB));
        Cout = color(redRGB + white, greenRGB + white, blueRGB + white);
    }

}