#include "OpenPBRSurface.h"

shader AutolibSurfaceComponentSeperate [[
    string category = "autolib"
]] (
    OpenPBRSurface mat = {},
    output OpenPBRBase Base = {},
    output OpenPBRSpecular Specular = {},
    output OpenPBRTransmission Transmission = {},
    output OpenPBRSubsurface Subsurface = {},
    output OpenPBRCoat Coat = {},
    output OpenPBRFuzz Fuzz = {},
    output OpenPBRThinFilm ThinFilm = {},
    output OpenPBREmission Emission = {},
    output OpenPBRGeometry Geometry = {}
) {
    Base = mat.base;
    Specular = mat.specular;
    Transmission = mat.transmission;
    Subsurface = mat.subsurface;
    Coat = mat.coat;
    Fuzz = mat.fuzz;
    ThinFilm = mat.thin_film;
    Emission = mat.emission;
    Geometry = mat.geometry;
}
