#include "OpenPBRSurface.h"

shader AutolibOpenPBRSpecularSeparate [[
    string category = "autolib"
]] (
    OpenPBRSpecular In = {},
    output float Weight = 0,
    output color Color = 0,
    output float Roughness = 0,
    output float RoughnessAnisotropy = 0,
    output float Haze = 0,
    output float HazeSpread = 0,
    output float IOR = 1.5
) {
    Weight = In.weight;
    Color = In.col;
    Roughness = In.roughness;
    RoughnessAnisotropy = In.roughness_anisotropy;
    Haze = In.haze;
    HazeSpread = In.haze_spread;
    IOR = In.ior;
}
