#include "OpenPBRSurface.h"

shader AutolibSurfaceMerge [[
    string category = "autolib"
]] (
    OpenPBRBase Base = {},
    OpenPBRSpecular Specular = {},
    OpenPBRTransmission Transmission = {},
    OpenPBRSubsurface Subsurface = {},
    OpenPBRCoat Coat = {},
    OpenPBRFuzz Fuzz = {},
    OpenPBRThinFilm ThinFilm = {},
    OpenPBREmission Emission = {},
    OpenPBRGeometry Geometry = {},
    output OpenPBRSurface Mat = {}
) {
    Mat.base = Base;
    Mat.specular = Specular;
    Mat.transmission = Transmission;
    Mat.subsurface = Subsurface;
    Mat.coat = Coat;
    Mat.fuzz = Fuzz;
    Mat.thin_film = ThinFilm;
    Mat.emission = Emission;
    Mat.geometry = Geometry;
}
