#include "OpenPBRSurface.h"

shader AutolibOpenPBRTransmissionSeparate [[
    string category = "autolib"
]] (
    OpenPBRTransmission In = {},
    output float Weight = 0,
    output color Color = 0,
    output float Depth = 0,
    output color Scatter = 0,
    output float ScatterAnisotropy = 0,
    output float DispersionScale = 0,
    output float DispersionAbbeNumber = 0
) {
    Weight = In.weight;
    Color = In.col;
    Depth = In.depth;
    Scatter = In.scatter;
    ScatterAnisotropy = In.scatter_anisotropy;
    DispersionScale = In.dispersion_scale;
    DispersionAbbeNumber = In.dispersion_abbe_number;
}
