#include "OpenPBRSurface.h"

shader AutolibOpenPBRSubsurfaceSeparate [[
    string category = "autolib"
]] (
    OpenPBRSubsurface In = {},
    output float Weight = 0,
    output color Color = 0,
    output float Radius = 0,
    output color RadiusScale = 0,
    output float ScatterAnisotropy = 0
) {
    Weight = In.weight;
    Color = In.col;
    Radius = In.radius;
    RadiusScale = In.radius_scale;
    ScatterAnisotropy = In.scatter_anisotropy;
}
