// AutolibCarbonFiberMaterial

shader AutolibCarbonFiberMaterial [[ 
    string category = "autolib"
]] (
    float fiberNoise = 0.0 [[ string page = "Fiber" ]],
    float fiberBump = 0.0 [[ string page = "Fiber" ]],
    normal fiberBumpedNormal = 0 [[ string page = "Fiber" ]],
    vector fiberRotation = 0 [[ string page = "Fiber" ]],

    float fiberStrandBoost = 1.5 [[ string doc = "Boost the bump of the fiber strands", float min = 0, float max = 3 ]],
    float fiberSpecularWeight = 0.8 [[ string doc = "Specular amount of the carbon fiber weaves", float min = 0, float max = 1 ]],

    color resinTint = color(0.3, 0.3, 0.27) [[ string doc = "Tint color of the resin" ]],
	float resinWeight = 1.0 [[ string page = "Clearcoat", float min = 0.0, float max = 1.0 ]],
    normal resinNormal = N [[ string page = "Clearcoat" ]],
    vector resinTangent = 0 [[ string page = "Clearcoat" ]],
	float resinAnisotropy = 0.0 [[ string page = "Clearcoat", float min = 0.0, float max = 1.0 ]],
	float resinRoughness = 0.05 [[ string page = "Clearcoat", float min = 0.0, float max = 1.0 ]],
	float resinIOR = 1.4 [[ string page = "Clearcoat", float min = 1.0, float max = 3.0 ]],
	float resinExponent = 5 [[ string page = "Clearcoat", float min = 0.0, float max = 10.0 ]],

    output closure color Cout = 0
) {
    float fiberBumpiness = fiberBump * pow(fiberNoise, fiberStrandBoost);

    closure color fiberBase = oren_nayar_diffuse_bsdf(Ng, color(0.01), 1.0);

    float roughnessAlong = 0.1 * fiberBumpiness; // Very smooth along fiber direction
    float roughnessAcross = 0.95 * fiberBumpiness; // Rougher across fiber direction

    closure color fiberSpecular = fiberSpecularWeight * generalized_schlick_bsdf(
        fiberBumpedNormal, fiberRotation,
        resinTint, // reflection_tint
        color(0), // transmission_tint
        roughnessAcross, // roughness_y (across fiber)
        roughnessAlong, // roughness_x (along fiber)
        color(0.04, 0.04, 0.04), // f0
        color(1, 1, 1), // f90
        5, // exponent
        "ggx" // distribution
    );

    closure color fiberLayer = layer(fiberSpecular, fiberBase);

	closure color resinBase = resinWeight * generalized_schlick_bsdf(
		fiberBumpedNormal, resinTangent,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		color(0.04), // f0
		color(1, 1, 1), // f90
		resinExponent, // exponent
		"ggx" // distribution
	);

	closure color resinTop = resinWeight * dielectric_bsdf(
		fiberBumpedNormal, resinTangent,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		resinIOR, // IOR
		"ggx"
	);

    Cout = layer(layer(resinTop, resinBase), fiberLayer);
}