#include "OpenPBRSurface.h"

shader AutolibOpenPBRGeometryCreate [[
    string category = "autolib"
]] (
    float Opacity = 1  [[ float min = 0, float max = 1 ]],
    int ThinWalled = 0  [[ string widget = "boolean" ]],
    normal Normal = N  [[ string widget = "null" ]],
    normal CoatNormal = N  [[ string widget = "null" ]],
    vector Tangent = dPdu  [[ string widget = "null" ]],
    vector CoatTangent = dPdu  [[ string widget = "null" ]],
    output OpenPBRGeometry Out = {}
) {
    Out.opacity = Opacity;
    Out.thin_walled = ThinWalled;
    Out.norm = Normal;
    Out.coat_normal = CoatNormal;
    Out.tangent = Tangent;
    Out.coat_tangent = CoatTangent;
}
