#include "OpenPBRSurfaceCombine.h"

shader AutolibSurfaceCombine [[
    string category = "autolib"
]] (
    float Factor = 0.5  [[ float min = 0.0, float max = 1.0 ]],
    OpenPBRSurface MaterialA = {},
    OpenPBRSurface MaterialB = {},
    output OpenPBRSurface mat = {}
) {
    float x = clamp(Factor, 0, 1);

    if (!isconnected(MaterialA) || x == 1) {
        mat = MaterialB;
        return;
    }
    if (!isconnected(MaterialB) || x == 0) {
        mat = MaterialA;
        return;
    }

    if (MaterialA.geometry.thin_walled != MaterialB.geometry.thin_walled) {
        printf(
            "Error in AutolibSurfaceCombine: cannot combine thin-walled" 
            "and non-thin-walled materials. MaterialA thin_walled = %d, "
            "MaterialB thin_walled = %d\n", 
            MaterialA.geometry.thin_walled, 
            MaterialB.geometry.thin_walled);
        exit();
    }

    mat.base = mix_base(MaterialA.base, MaterialB.base, x);
    mat.specular = mix_specular(MaterialA.specular, MaterialB.specular, x);
    mat.transmission = mix_transmission(MaterialA.transmission, MaterialB.transmission, x);
    mat.subsurface = mix_subsurface(MaterialA.subsurface, MaterialB.subsurface, x);
    mat.coat = mix_coat(MaterialA.coat, MaterialB.coat, x);
    mat.fuzz = mix_fuzz(MaterialA.fuzz, MaterialB.fuzz, x);
    mat.thin_film = mix_thin_film(MaterialA.thin_film, MaterialB.thin_film, x);
    mat.emission = mix_emission(MaterialA.emission, MaterialB.emission, x);
    mat.geometry = mix_geometry(MaterialA.geometry, MaterialB.geometry, x);
}
