#include "OpenPBRSurface.h"

shader AutolibOpenPBRSubsurfaceCreate [[
    string category = "autolib"
]] (
    float Weight = 0  [[ float min = 0, float max = 1 ]],
    color Color = 1,
    float Radius = 1  [[ float min = 0 ]],
    color RadiusScale = 1,
    float ScatterAnisotropy = 0  [[ float min = -1, float max = 1 ]],
    output OpenPBRSubsurface Out = {}
) {
    Out.weight = Weight;
    Out.col = Color;
    Out.radius = Radius;
    Out.radius_scale = RadiusScale;
    Out.scatter_anisotropy = ScatterAnisotropy;
}
