#include "OpenPBRSurface.h"

shader AutolibOpenPBRThinFilmCreate [[
    string category = "autolib"
]] (
    float Weight = 0  [[ float min = 0, float max = 1 ]],
    float Thickness = 0.5  [[ float min = 0, float max = 1 ]],
    float IOR = 1.4  [[ float min = 1, float max = 3.0 ]],
    output OpenPBRThinFilm Out = {}
) {
    Out.weight = Weight;
    Out.thickness = Thickness;
    Out.ior = IOR;
}
