#ifndef NOT_MTX_IMPL   
    #define ENTRY_CARBON_FIBER void 
#endif

#ifndef ENTRY_CARBON_FIBER
	#define ENTRY_CARBON_FIBER shader
    #define  DEFAULT_CARBON_FIBER(x) = x
#else
    #define  DEFAULT_CARBON_FIBER(x)
#endif

#include "Utility/TangentField.h"

struct WeaveData {
    float mask;
    vector position;
    vector textureCoordinates;
    float segmentFactor;
};

WeaveData createWeaves(
    vector coordinates
) {

    float scale = 4; // dimension of the grid weave

    WeaveData weaveData;

    vector coordinatesPrime = ((coordinates * scale) / 2) + 1;

    float x = coordinatesPrime.x / scale;
    float moduloX = mod(x, 1) * scale;
    float floorModuloX = floor(moduloX);
    float xy = floorModuloX + coordinatesPrime.y;

    //float mask
    float absModuloScaledXY = abs(mod(xy / scale, 1));
    weaveData.mask = step(0.5, absModuloScaledXY);

    float scaledXY = xy / (scale / 2);
    weaveData.segmentFactor = mod(scaledXY, 1);

    float scaledSegmentFactor = weaveData.segmentFactor * (scale / 2);
    weaveData.textureCoordinates.x = mod(coordinatesPrime.x, 1);
    weaveData.textureCoordinates.y = scaledSegmentFactor;

    weaveData.position.x = floor(coordinatesPrime.x);
    weaveData.position.y = floor(scaledXY);

    return weaveData;
}

float mirrorCurve(float input, float exponent) {
    float inverseClamp = 1-clamp(input, 0, 1);
    float factor = step(0.5, input);
    float stepped = mix(input, inverseClamp, factor);
    return pow(clamp(stepped, 0, 1), 1/exponent);
}

vector mirrorCurve(vector input, float exponent) {
    vector inverseClamp = 1-clamp(input, 0, 1);
    vector factor = step(0.5, input);
    vector stepped = mix(input, inverseClamp, factor);
    return pow(clamp(stepped, 0, 1), 1/exponent);
}

struct WeaveParams {
    float zGamma;
};

void displacedWeaves (
    WeaveParams params,
    WeaveData weaveControlData,
    WeaveData weaveData,
    output float fiberNoise,
    output float fiberBump,
    output normal fiberRotation
) {
    vector mixedTextureCoordinates = mix(weaveControlData.textureCoordinates, weaveData.textureCoordinates, weaveData.mask);
    vector mixedPositionCoordinates = mix(weaveControlData.position, weaveData.position, weaveControlData.mask);

    // Noise
    vector biasedFactor = (mixedPositionCoordinates + mixedTextureCoordinates) * vector(500, 0.0001, 0);
    float noisy = noise("cell", biasedFactor);
    fiberNoise = noisy;//mix(0.0, 1, noisy);

    //Bump
    float weaveFactorBump = mix(weaveControlData.segmentFactor, weaveData.segmentFactor, weaveControlData.mask);
    float iBump = mirrorCurve(weaveFactorBump, params.zGamma);
    float jBump = mirrorCurve(mixedTextureCoordinates.x, 6);
    //fiberBump = iBump;
    fiberBump = min(iBump, jBump);

    //Normal
    //float iVecFactor = 2 * (1 - weaveControlData.segmentFactor) - 1;
    //float jVecFactor = 2 * weaveData.segmentFactor - 1;
    float iVecFactor = (1 - weaveControlData.segmentFactor);
    float jVecFactor = weaveData.segmentFactor;

    vector iVec = vector(iVecFactor, 0, 0);
    vector jVec = vector(0, jVecFactor, 0);
    vector iWeaveFactorNormal = mix(iVec, jVec, weaveControlData.mask);

    //float anotherFactor = (2 * pow(clamp(mixedTextureCoordinates.x, 0, 1), 0.1) - 1);
    float anotherFactor = pow(clamp(mixedTextureCoordinates.x, 0, 1), 0.1);


    iVec = vector(anotherFactor, 0, 0);
    jVec = vector(0, anotherFactor, 0);
    vector jWeaveFactorNormal = mix(iVec, jVec, weaveControlData.mask);

    fiberRotation = min(iWeaveFactorNormal, jWeaveFactorNormal);
    //fiberRotation = vector(iWeaveFactorNormal);
}

normal getBumpedNormal( vector centerColor, 
                        vector uColor, 
                        vector vColor, 
                        float bumpAmount
) {
	vector worldTangent = normalize(dPdu);
	vector worldBitangent = normalize(dPdv);
	vector worldNormal = normalize(N);
	
    vector average = vector(0.3333333);
    float center = dot(average, centerColor);
    float ddu = center - dot(average, uColor);
    float ddv = center - dot(average, vColor);
	
	float inverseBumpAmount = 1.0 / bumpAmount;
	
    return normalize(ddu * worldTangent + ddv * worldBitangent + inverseBumpAmount * worldNormal);
}

ENTRY_CARBON_FIBER CarbonFiber (
    point UV  DEFAULT_CARBON_FIBER(point(u, v, 0)),

    vector fiberScale  DEFAULT_CARBON_FIBER(vector(64, 32, 0)) [[ string doc = "Scale axis of the carbon fiber pattern", vector uimin = vector(64, 32, 0) ]],
    float fiberZGamma  DEFAULT_CARBON_FIBER(1.5) [[ string doc = "Controls the sharpness of the fiber strands", float uimin = 0.1, float uimax = 4.0 ]],

    float fiberBumpStrength  DEFAULT_CARBON_FIBER(0.1) [[ string doc = "Strength of the bump effect", float uimin = 0, float uimax = 1 ]],
    float fiberStrandBoost  DEFAULT_CARBON_FIBER(1.5) [[ string doc = "Boost the bump of the fiber strands", float uimin = 0, float uimax = 3 ]],
    float fiberSpecularWeight  DEFAULT_CARBON_FIBER(0.8) [[ string doc = "specular Amount of the carbon Fiber weaves", float uimin = 0, float uimax = 1 ]],

    color resinTint  DEFAULT_CARBON_FIBER(color(0.3, 0.3, 0.27)) [[ string doc = "Tint color of the resin" ]],
	float resinWeight  DEFAULT_CARBON_FIBER(1.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinAnisotropy  DEFAULT_CARBON_FIBER(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinRoughness  DEFAULT_CARBON_FIBER(0.05)[[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinRotation  DEFAULT_CARBON_FIBER(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinIOR  DEFAULT_CARBON_FIBER(1.4) [[ string uifolder = "Clearcoat", float uimin = 1.0, float uimax = 3.0 ]],
	float resinExponent  DEFAULT_CARBON_FIBER(5) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 10.0 ]],

    output closure color Cout  DEFAULT_CARBON_FIBER(0),
    output normal outTangent = 0
) {
    point fiberUV = UV * fiberScale;
    point weaveControlDataCoordinates = fiberUV;
    point weaveDataCoordinates = vector(fiberUV.y, fiberUV.x, 0);
    
    // Sample neighboring heights using texture derivatives
    point weaveControlDataCoordinatesU = weaveControlDataCoordinates + vector(Dx(weaveControlDataCoordinates));
    point weaveControlDataCoordinatesV = weaveControlDataCoordinates + vector(Dy(weaveControlDataCoordinates));

    WeaveData weaveControlData = createWeaves(weaveControlDataCoordinates);
    WeaveData weaveData = createWeaves(weaveDataCoordinates);
    
    WeaveData weaveControlDataU = createWeaves(weaveControlDataCoordinatesU);
    WeaveData weaveControlDataV = createWeaves(weaveControlDataCoordinatesV);
    
    float fiberNoise;
    float fiberBump;
    normal fiberRotation;
    
    float fiberNoiseU, fiberBumpU;
    normal fiberRotationU;
    
    float fiberNoiseV, fiberBumpV;
    normal fiberRotationV;

    WeaveParams weaveParams;
    weaveParams.zGamma = fiberZGamma;

    displacedWeaves(weaveParams, weaveControlData, weaveData, fiberNoise, fiberBump, fiberRotation);
    displacedWeaves(weaveParams, weaveControlDataU, weaveData, fiberNoiseU, fiberBumpU, fiberRotationU);
    displacedWeaves(weaveParams, weaveControlDataV, weaveData, fiberNoiseV, fiberBumpV, fiberRotationV);
    
    float fiberBumpiness = fiberBump * pow(fiberNoise, fiberStrandBoost);

    vector centerHeight = vector(fiberBump);
    vector uHeight = vector(fiberBumpU);
    vector vHeight = vector(fiberBumpV);
    
    normal bumpedNormal = getBumpedNormal(centerHeight, uHeight, vHeight, fiberBumpStrength);

    color baseColor = color(0.01);
    closure color fiberBase = burley_diffuse_bsdf(Ng, baseColor, 1.0);

    vector fiberTangent;

    TangentField(
        0, // float inputRotation,
        fiberRotation, // vector inputVector,
        0, // float rotationOffset
        1.0, // float rotationRange,
        1, // int centeredVectors
        fiberTangent
    );

    vector weaveDirection = weaveControlData.mask > 0.5 ? vector(1,0,0) : vector(0,1,0);

    float weaveVariation = mix(0.5, 1.0, fiberBumpiness); // map bumpiness to 0.5 to 1.0
    
    float roughnessAlong = 0.1 * fiberBumpiness; // Very smooth along fiber direction
    float roughnessAcross = 0.95 * fiberBumpiness; // Rougher across fiber direction
    
    closure color fiberSpecular = fiberSpecularWeight * generalized_schlick_bsdf(
        bumpedNormal, fiberTangent,
        resinTint, // reflection_tint
        color(0), // transmission_tint
        roughnessAcross, // roughness_y (across fiber)
        roughnessAlong, // roughness_x (along fiber)
        color(0.04,0.04,0.04), // f0
        color(1,1,1), // f90
        5, // exponent
        "ggx" // distribution
    );
    
    closure color fiberLayer = layer(fiberSpecular, fiberBase);

    

	vector T = vector(cos(2 * M_PI * resinRotation), sin(2 * M_PI * resinRotation), 0);

	closure color resinBase = resinWeight * generalized_schlick_bsdf(
		bumpedNormal, T,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		color(0.04), // f0
		color(1,1,1), // f90
		resinExponent, // exponent
		"ggx" // distribution
	);

	closure color resinTop = resinWeight * dielectric_bsdf(
		N, T,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		resinIOR, // IOR
		"ggx"
	);

    closure color resinLayer = layer(resinTop, resinBase);
    
    Cout = layer(resinLayer, fiberLayer);
    Cout = fiberLayer;
}