shader AutolibMix [[
    string category = "autolib"
]] (
    float Mixer = 0 [[ string widget = "number", int slider = 1, float slidermin = 0, float slidermax = 1 ]],
    vector VectorA = 0,
    vector VectorB = 1,
    int Clamp = 0 [[ string widget = "checkBox", int min = 0, int max = 1 ]],

    output vector XYZ = 0
) {
    float clampedMixer = Mixer;
    if (Clamp == 1) {
        clampedMixer = clamp(Mixer, 0.0, 1.0);
    }

    if (clampedMixer <= 0.0) {
        XYZ = VectorA;
        return;
    } else if (clampedMixer >= 1.0) {
        XYZ = VectorB;
        return;
    }

    XYZ = mix(VectorA, VectorB, clampedMixer);
}