#ifndef SOLO_SHADER
    #define ENTRY_METALLIC_FLAKE_LAYER void
#endif

#ifndef ENTRY_METALLIC_FLAKE_LAYER
    #define ENTRY_METALLIC_FLAKE_LAYER surface
    #define DEFAULT_METALLIC_FLAKE_LAYER(x) = x
#else
    #define DEFAULT_METALLIC_FLAKE_LAYER(x)
#endif

ENTRY_METALLIC_FLAKE_LAYER AutolibPaintLayer [[
    string nodegroup = "autolib",
    int isdefaultversion = 1,
    string version = "0.1"
]] (
    float flakeAlpha  DEFAULT_METALLIC_FLAKE_LAYER(0.0),
    normal flakeNormal  DEFAULT_METALLIC_FLAKE_LAYER(normal(0.5, 0.5, 1.0)),

    // Flakes
    float flakeRandomize  DEFAULT_METALLIC_FLAKE_LAYER(0.2)  [[ string uifolder = "Flakes", float uimin = 0.0, float uimax = 1.0 ]],
    float flakeWeight  DEFAULT_METALLIC_FLAKE_LAYER(1.0)  [[ string uifolder = "Flakes", float uimin = 0.0, float uimax = 1.0 ]],
    color flakeReflectivity  DEFAULT_METALLIC_FLAKE_LAYER(color(0.95, 0.95, 0.95)) [[ string uifolder = "Flakes" ]],
    color flakeEdgeTint  DEFAULT_METALLIC_FLAKE_LAYER(color(1.0, 1.0, 1.0))    [[ string uifolder = "Flakes" ]],
    float flakeRoughness  DEFAULT_METALLIC_FLAKE_LAYER(0.1)  [[ string uifolder = "Flakes", float uimin = 0.0, float uimax = 1.0 ]],

    // Base paint
    float baseAmount  DEFAULT_METALLIC_FLAKE_LAYER(0.5)  [[ string uifolder = "Base", float uimin = 0.0, float uimax = 1.0 ]],
    float baseWeight  DEFAULT_METALLIC_FLAKE_LAYER(1.0)  [[ string uifolder = "Base", float uimin = 0.0, float uimax = 1.0 ]],
    color baseColor  DEFAULT_METALLIC_FLAKE_LAYER(color(1.0, 0.1, 0.1)) [[ string uifolder = "Base" ]],
    float baseRoughness  DEFAULT_METALLIC_FLAKE_LAYER(0.5)  [[ string uifolder = "Base", float uimin = 0.0, float uimax = 1.0 ]],
    float baseIOR  DEFAULT_METALLIC_FLAKE_LAYER(1.9)  [[ string uifolder = "Base", float uimin = 1.0, float uimax = 3.0 ]],

    // Layer beneath this one
    closure color underLayer DEFAULT_METALLIC_FLAKE_LAYER(0),

    output closure color out DEFAULT_METALLIC_FLAKE_LAYER(0)
) {
    normal finalNormal = mix(Ng, flakeNormal, flakeRandomize);

    closure color thisLayer;

    float baseDiffuseWeight = baseWeight * baseAmount;

    if (flakeAlpha > 0.5) {
        color flakeIOR, flakeExtinction;
        artistic_ior(flakeReflectivity, flakeEdgeTint, flakeIOR, flakeExtinction);

        closure color flake = conductor_bsdf(
            finalNormal, 0,
            flakeRoughness, // roughness_x
            flakeRoughness, // roughness_y
            flakeIOR,       // ior
            flakeExtinction, // extinction
            "ggx"
        );

        thisLayer = flakeWeight * flake;

    } else {
        closure color laquer = dielectric_bsdf(
            N, 0,
            baseColor,     // reflection_tint
            0, // transmission_tint
            baseRoughness, // roughness_x
            baseRoughness, // roughness_y
            baseIOR,      // ior
            "ggx"
        );

        closure color baseDiffuse = baseDiffuseWeight * oren_nayar_diffuse_bsdf(
            N, baseColor, baseRoughness
        );
        // depending on how much the base paint has 
        // been reduced, it is best to repersent this 
        // in a diffuse component 

        thisLayer = baseWeight * layer(laquer, baseDiffuse);
    }


    out = layer(thisLayer, (1 - baseDiffuseWeight) * underLayer);
}