#ifndef SOLO_SHADER   
    #define ENTRY_CARBON_FIBER_MATERIAL void 
#endif

#ifndef ENTRY_CARBON_FIBER_MATERIAL
	#define ENTRY_CARBON_FIBER_MATERIAL surface
    #define DEFAULT_CARBON_FIBER_MATERIAL(x) = x
#else
    #define DEFAULT_CARBON_FIBER_MATERIAL(x)
#endif

ENTRY_CARBON_FIBER_MATERIAL AutolibCarbonFiberMaterial [[ 
    string nodegroup = "autolib",
    int isdefaultversion = 1,
    string version = "0.1"
]] (
    float fiberNoise  DEFAULT_CARBON_FIBER_MATERIAL(0.0),
    float fiberBump  DEFAULT_CARBON_FIBER_MATERIAL(0.0),
    normal fiberBumpedNormal  DEFAULT_CARBON_FIBER_MATERIAL(0),
    vector fiberRotation  DEFAULT_CARBON_FIBER_MATERIAL(0),

    float fiberStrandBoost  DEFAULT_CARBON_FIBER_MATERIAL(1.5) [[ string doc = "Boost the bump of the fiber strands", float uimin = 0, float uimax = 3 ]],
    float fiberSpecularWeight  DEFAULT_CARBON_FIBER_MATERIAL(0.8) [[ string doc = "Specular amount of the carbon fiber weaves", float uimin = 0, float uimax = 1 ]],

    color resinTint  DEFAULT_CARBON_FIBER_MATERIAL(color(0.3, 0.3, 0.27)) [[ string doc = "Tint color of the resin" ]],
	float resinWeight  DEFAULT_CARBON_FIBER_MATERIAL(1.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinAnisotropy  DEFAULT_CARBON_FIBER_MATERIAL(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinRoughness  DEFAULT_CARBON_FIBER_MATERIAL(0.05) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinRotation  DEFAULT_CARBON_FIBER_MATERIAL(0.0) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 1.0 ]],
	float resinIOR  DEFAULT_CARBON_FIBER_MATERIAL(1.4) [[ string uifolder = "Clearcoat", float uimin = 1.0, float uimax = 3.0 ]],
	float resinExponent  DEFAULT_CARBON_FIBER_MATERIAL(5) [[ string uifolder = "Clearcoat", float uimin = 0.0, float uimax = 10.0 ]],

    output closure color out  DEFAULT_CARBON_FIBER_MATERIAL(0)
) {
    float fiberBumpiness = fiberBump * pow(fiberNoise, fiberStrandBoost);

    closure color fiberBase = oren_nayar_diffuse_bsdf(Ng, color(0.01), 1.0);

    float roughnessAlong = 0.1 * fiberBumpiness; // Very smooth along fiber direction
    float roughnessAcross = 0.95 * fiberBumpiness; // Rougher across fiber direction

    closure color fiberSpecular = fiberSpecularWeight * generalized_schlick_bsdf(
        fiberBumpedNormal, fiberRotation,
        resinTint, // reflection_tint
        color(0), // transmission_tint
        roughnessAcross, // roughness_y (across fiber)
        roughnessAlong, // roughness_x (along fiber)
        color(0.04, 0.04, 0.04), // f0
        color(1, 1, 1), // f90
        5, // exponent
        "ggx" // distribution
    );

    closure color fiberLayer = layer(fiberSpecular, fiberBase);

	vector T = vector(cos(2 * M_PI * resinRotation), sin(2 * M_PI * resinRotation), 0);

	closure color resinBase = resinWeight * generalized_schlick_bsdf(
		fiberBumpedNormal, T,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		color(0.04), // f0
		color(1, 1, 1), // f90
		resinExponent, // exponent
		"ggx" // distribution
	);

	closure color resinTop = resinWeight * dielectric_bsdf(
		fiberBumpedNormal, T,
		resinTint, // reflection_tint
		color(0.0), // transmission_tint
		resinRoughness, // roughness_y
		resinRoughness * (1.0 - resinAnisotropy), // roughness_x
		resinIOR, // IOR
		"ggx"
	);

    out = layer(layer(resinTop, resinBase), fiberLayer);
}