#ifndef SOLO_SHADER
    #define ENTRY_CLEARCOAT_LAYER void
#endif

#ifndef ENTRY_CLEARCOAT_LAYER
    #define ENTRY_CLEARCOAT_LAYER surface
    #define DEFAULT_CLEARCOAT_LAYER(x) = x
#else
    #define DEFAULT_CLEARCOAT_LAYER(x)
#endif

ENTRY_CLEARCOAT_LAYER ClearcoatLayer [[
    string nodegroup = "autolib",
    int isdefaultversion = 1,
    string version = "0.1"
]] (
    float weight  DEFAULT_CLEARCOAT_LAYER(1.0)  [[ float uimin = 0.0, float uimax = 1.0 ]],
    float roughness  DEFAULT_CLEARCOAT_LAYER(0.05) [[ float uimin = 0.0, float uimax = 1.0 ]],
    float anisotropy DEFAULT_CLEARCOAT_LAYER(0.0)  [[ float uimin = 0.0, float uimax = 1.0 ]],
    float rotation  DEFAULT_CLEARCOAT_LAYER(0.0)  [[ float uimin = 0.0, float uimax = 1.0 ]],
    float ior DEFAULT_CLEARCOAT_LAYER(1.4)  [[ float uimin = 1.0, float uimax = 3.0 ]],
    float exponent   DEFAULT_CLEARCOAT_LAYER(5.0)  [[ float uimin = 0.0, float uimax = 10.0 ]],

    closure color underlayer DEFAULT_CLEARCOAT_LAYER(0),

    output closure color Cout DEFAULT_CLEARCOAT_LAYER(0)
) {
    vector T = vector(cos(2 * M_PI * rotation), sin(2 * M_PI * rotation), 0);

    float roughnessX = roughness * (1.0 - anisotropy);

    closure color clearcoatBase = generalized_schlick_bsdf(
        N, T,
        color(1.0), // reflection_tint
        color(0.0), // transmission_tint
        roughness, // roughness_y
        roughnessX,         // roughness_x
        color(0.04),        // f0
        color(1, 1, 1),     // f90
        exponent,  // exponent
        "ggx"
    );

    closure color clearcoatTop = dielectric_bsdf(
        N, T,
        color(1.0), // reflection_tint
        color(0.0), // transmission_tint
        roughness, // roughness_y
        roughnessX,         // roughness_x
        ior,
        "ggx"
    );

    Cout = weight * layer(layer(clearcoatTop, clearcoatBase), underlayer);
}