#ifdef NO_ENTRY 
    #define ENTRY_HALFTONE_DOTS void 
#endif

#ifndef ENTRY_HALFTONE_DOTS
    #define  DEFAULT_HALFTONE_DOTS(x) = x
	#define ENTRY_HALFTONE_DOTS shader
#else
    #define  DEFAULT_HALFTONE_DOTS(x)
#endif

ENTRY_HALFTONE_DOTS HalftoneDots(
	vector UVW  DEFAULT_HALFTONE_DOTS(transform("raster", P))  [[ string description = "The input coordinate. If not connected, uses screen pixel space" ]],
	vector scale  DEFAULT_HALFTONE_DOTS(vector(8.0, 8.0, 8.0))  [[ string description = "This size of the dots. In the default screen space mapping, this is in pixels." ]],
	float  angle  DEFAULT_HALFTONE_DOTS(45.0)  [[ string description = "angle of the Halftoning" ]],	
	color  inputValue  DEFAULT_HALFTONE_DOTS(0.25)  [[ string description = "The input value defining the size of the dots to yield the right halftone density. " ]],	
	float  fuzz  DEFAULT_HALFTONE_DOTS(0.1)  [[ float uiMin = 0.0, float uiMax = 2.0 ]],
	color  dotsColor  DEFAULT_HALFTONE_DOTS(0.0)  [[ string description = "The color of the dots" ]],		
	color  backgroundColor  DEFAULT_HALFTONE_DOTS(1.0)  [[ string description = "The color of the space between the dots" ]],		

	output color dots  DEFAULT_HALFTONE_DOTS(0)
) {
	vector pos = rotate(UVW, radians(angle), 0.0, vector(0.0,0.0,1.0));
	pos = vector(pos.x / scale.x, pos.y / scale.y, 0.0);
	if (scale.x == 0.0) {
		pos.x = 0.5;
	} if (scale.y == 0.0) {
		pos.y = 0.5;
	}
	
	pos = pos - floor(pos);
	
	float dist = 1.0 - (distance(vector(0.5,0.5,0.0), pos) / (sqrt(2.0) / 2.5));	
	color factor = smoothstep(-fuzz, 0.0, inputValue - sqrt(max(0,dist)));
		
	dots = mix(dotsColor, backgroundColor, factor);
}