#ifndef SOLO_SHADER   
    #define ENTRY_SPLATTER void 
#endif

#ifndef ENTRY_SPLATTER
    #define DEFAULT_SPLATTER(x) = x
    #define ENTRY_SPLATTER shader
#else
    #define DEFAULT_SPLATTER(x)
#endif

#include "SplatterLayerParams.h"

point randomCellPosition(int x, int y, float jitter, int seed) {
    vector off = cellnoise(vector(x, y, 0), seed);
    off -= 0.5;
    off *= jitter;
    off += 0.5;
    return point(x + off[0], y + off[1], 0);
}

float randomRadius(int x, int y, float minRadius, float maxRadius) {
    float randomValue = noise("cell", vector(x + 123.456, y + 789.012, 0));
    
    return minRadius + randomValue * (maxRadius - minRadius);
}

float sigmoidMask(float x, float low, float center, float sharpness) {
    float k = 1.0 / max(1e-6, sharpness);
    float s = 1.0 / (1.0 + exp(-k * (x - center)));
    return low + (1.0 - low) * s;
}

float smoothMin(float a, float b, float k) {
    float res = -log(exp(-k*a) + exp(-k*b)) / k;
    return res;
}

ENTRY_SPLATTER Splatter [[ 
    string nodegroup = "autolib", 
]] (
    point UV  DEFAULT_SPLATTER(0),
    SplatterLayerParams layerParams DEFAULT_SPLATTER({}),
    output float height  DEFAULT_SPLATTER(0.0),
    output float mask  DEFAULT_SPLATTER(0.0)
) {    
    int cellX = (int)floor(UV[0]);
    int cellY = (int)floor(UV[1]);
    
    vector localPos = UV - vector(cellX, cellY, 0);
    
    float noisedDistance = 1e6;
    float smoothDistance = 1e6;

    for (int x = -1; x <= 1; x++) {
        for (int y = -1; y <= 1; y++) {
            point cellCenter = randomCellPosition(cellX + x, cellY + y, layerParams.jitter, layerParams.seed);
        
            vector diff = UV - cellCenter;
            float edgeDistance = length(diff);
        
            float circleRandomSeed = noise("cell", vector(cellX + x + 456.789 + layerParams.seed, cellY + y + 321.654 + layerParams.seed, layerParams.seed)) * 1000.0;
            float angleNoise = layerParams.spikeFrequency * noise("uperlin", circleRandomSeed);
            float angle = (atan2(diff.y, diff.x) / (2.0 * M_PI)) + 0.5;
        
            float addNoise = pow(layerParams.spikePeak, noise("snoise", (angle * angleNoise) - circleRandomSeed));
            
            if (layerParams.spikeTrimWidth > 0.0) {
                float distFromBoundary = min(angle, 1.0 - angle);
                float edgeFactor = smoothstep(0.0, layerParams.spikeTrimWidth, distFromBoundary);
                addNoise = addNoise * edgeFactor;
            }

            addNoise = ((1.0 - layerParams.spikeAmount) * addNoise) + layerParams.spikeAmount;

            float radius = randomRadius(cellX + x, cellY + y, layerParams.minRadius * layerParams.scaleRadius, layerParams.maxRadius * layerParams.scaleRadius);
            float edgeNoisedDistance = edgeDistance - (radius * addNoise);
        
            if (edgeNoisedDistance < noisedDistance) {
                noisedDistance = edgeNoisedDistance;
            }

            if (x == -1 && y == -1) {
                smoothDistance = edgeDistance;
            } else {
                smoothDistance = smoothMin(smoothDistance, edgeDistance, layerParams.unionSmoothness);
            }
        }
    }

    mask = 1.0 - smoothstep(0, layerParams.spikePerimeterSmoothness, noisedDistance);

    float heightProfile = sigmoidMask(smoothDistance, layerParams.basinHeight, layerParams.basinCenter, layerParams.basinSmoothness);
    height = (heightProfile * 1.40) * mask;
}
