#ifndef SOLO_SHADER   
    #define ENTRY_CREATE_SPLATTER_LAYER_PARAMS void 
#endif

#ifndef ENTRY_CREATE_SPLATTER_LAYER_PARAMS
    #define DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(x) = x
    #define ENTRY_CREATE_SPLATTER_LAYER_PARAMS shader
#else
    #define DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(x)
#endif

struct SplatterLayerParams {
    float scale;
    int seed;
    float jitter;
    float scaleRadius;
    float minRadius;
    float maxRadius;
    float unionSmoothness;

    float spikeAmount;
    float spikePeak;
    float spikeFrequency;
    float spikePerimeterSmoothness;
    float spikeTrimWidth;

    float basinHeight;
    float basinCenter;
    float basinSmoothness;

    //paint
    float splatterBumpStrength;
    color primerColor;
    
    //base layer params
    float baseWeight;
    color baseColor;
    float baseRoughness;
    float baseIOR;
    
    //metallic/flake layer params
    float flakeWeight;
    color flakeReflectivity;
    color flakeEdgeTint;
    float flakeRoughness;
};

ENTRY_CREATE_SPLATTER_LAYER_PARAMS CreateSplatterLayer [[
    string nodegroup = "autolib",
]] (
    float scale DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(1) [[ string uifolder = "Pattern" ]],
    int seed  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0) [[ string uifolder = "Pattern" ]],
    float jitter  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(1.0) [[ string uifolder = "Pattern" ]],
    float scaleRadius  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(1.0) [[ string uifolder = "Pattern" ]],
    float minRadius  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.1) [[ string uifolder = "Pattern" ]],
    float maxRadius  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.4) [[ string uifolder = "Pattern" ]],
    float unionSmoothness  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(8.0) [[ string uifolder = "Pattern", string doc = "Controls the smoothness between overlapping drops" ]],

    //splatter spikes control
    float spikeAmount  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.95) [[ string uifolder = "Spikes", string doc = "Controls the intensity of the spikes on the splatter", float uimin = 0.0, float uimax = 1.0 ]],
    float spikePeak  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(24.0) [[ string uifolder = "Spikes", string doc = "Controls the height of the peak spikes", float uimin = 1.0 ]],
    float spikeFrequency  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(12.0)  [[ string uifolder = "Spikes", string doc = "Higher values increase the number of spikes", float uimin = 0.0 ]],
    float spikePerimeterSmoothness  DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.01) [[ string uifolder = "Spikes", float uimin = 0.0, float uimax = 1.0 ]],
    float spikeTrimWidth DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.1) [[ string uifolder = "Spikes", string doc = "Width of the ramp zone at angle boundaries to smooth the seam", float uimin = 0.0, float uimax = 0.5 ]],

    float basinHeight DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.6) [[ string uifolder = "Basin", string doc = "Base height of the splatter basin", float uimin = 0.0, float uimax = 1.0 ]],
    float basinCenter DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.5) [[ string uifolder = "Basin", string doc = "The the inflection point where the basin rises to a parameter", float uimin = 0.0, float uimax = 1.0 ]],
    float basinSmoothness DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.5) [[ string uifolder = "Basin", string doc = "The the inflection point where the basin rises to a parameter", float uimin = 0.0, float uimax = 1.0 ]],

    float splatterBumpStrength DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.1),
    color primerColor DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(color(1)),

    float baseWeight DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(1.0),
    color baseColor DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(color(0.8)),
    float baseRoughness DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.5),
    float baseIOR DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(1.5),

    float flakeWeight DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.0),
    color flakeReflectivity DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(color(1)),
    color flakeEdgeTint DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(color(1)),
    float flakeRoughness DEFAULT_CREATE_SPLATTER_LAYER_PARAMS(0.3),

    output SplatterLayerParams params DEFAULT_CREATE_SPLATTER_LAYER_PARAMS({})
) {
    params.scale = scale;
    params.seed = seed;
    params.jitter = jitter;
    params.scaleRadius = scaleRadius;
    params.minRadius = minRadius;
    params.maxRadius = maxRadius;
    params.unionSmoothness = unionSmoothness;

    params.spikeAmount = spikeAmount;
    params.spikePeak = spikePeak;
    params.spikeFrequency = spikeFrequency;
    params.spikePerimeterSmoothness = spikePerimeterSmoothness;
    params.spikeTrimWidth = spikeTrimWidth;

    params.basinHeight = basinHeight;
    params.basinCenter = basinCenter;
    params.basinSmoothness = basinSmoothness;

    params.splatterBumpStrength = splatterBumpStrength;
    params.primerColor = primerColor;

    params.baseWeight = baseWeight;
    params.baseColor = baseColor;
    params.baseRoughness = baseRoughness;
    params.baseIOR = baseIOR;

    params.flakeWeight = flakeWeight;
    params.flakeReflectivity = flakeReflectivity;
    params.flakeEdgeTint = flakeEdgeTint;
    params.flakeRoughness = flakeRoughness;
}

SplatterLayerParams defaultSplatterLayerParams1(color layer1) {
    return {
        12,
        34, //int seed
        2.0, // float jitter
        0.65, // float scaleRadius
        0.005, // float minRadius
        0.15, // float maxRadius
        8.0, // float unionSmoothness

        //splatter spikes control
        0.9, // float spikeAmount
        12.0, // float spikePeak
        48.0, // float spikeFrequency
        0.01, // float spikePerimeterSmoothness
        0.0, //float spikeTrimWidth

        0.95, // float basinHeight
        0.3, // float basinCenter
        0.075, // float basinSmoothness 

        0.075, //float splatterBumpStrength 
        layer1, // color primerColor
        
        // base layer params
        1.0, // float baseWeight,
        layer1, // color baseColor,
        0.3, // float baseRoughness,
        1.4, // float baseIOR,
        
        // metallic/flake layer params
        1.0, // float flakeWeight,
        layer1, // color flakeReflectivity,
        layer1, // color flakeEdgeTint,
        0.1 // float flakeRoughness
    };
}

SplatterLayerParams defaultSplatterLayerParams2(color layer2) {
    return {
        36,
        433, // int seed
        2.0, // float jitter
        0.8, // float scaleRadius
        0.005, // float minRadius
        0.3, // float maxRadius
        8.0, // float unionSmoothness

        //splatter spikes control
        0.9, // float spikeAmount
        8, // float spikePeak
        36, // float spikeFrequency
        0.01, // float spikePerimeterSmoothness
        0.02, //float spikeTrimWidth

        0.95, // float basinHeight
        0.3, // float basinCenter
        0.075, // float basinSmoothness 

        0.075, //float splatterBumpStrength 
        layer2, // color primerColor
        
        // base layer params
        1.0, // float baseWeight,
        layer2, // color baseColor,
        0.3, // float baseRoughness,
        1.4, // float baseIOR,
        
        // metallic/flake layer params
        1.0, // float flakeWeight,
        layer2, // color flakeReflectivity,
        layer2, // color flakeEdgeTint,
        0.1 // float flakeRoughness
    };
}

SplatterLayerParams defaultSplatterLayerParams3(color layer3) {
    return {
        36,
        234, // int seed
        2.0, // float jitter
        0.8, // float scaleRadius
        0.005, // float minRadius
        0.3, // float maxRadius
        8.0, // float unionSmoothness

        //splatter spikes control
        0.9, // float spikeAmount
        8, // float spikePeak
        36, // float spikeFrequency
        0.01, // float spikePerimeterSmoothness
        0.02, //float spikeTrimWidth

        0.95, // float basinHeight
        0.3, // float basinCenter
        0.075, // float basinSmoothness 

        0.075, //float splatterBumpStrength 
        layer3, // color primerColor
        
        // base layer params
        1.0, // float baseWeight,
        layer3, // color baseColor,
        0.3, // float baseRoughness,
        1.4, // float baseIOR,
        
        // metallic/flake layer params
        1.0, // float flakeWeight,
        layer3, // color flakeReflectivity,
        layer3, // color flakeEdgeTint,
        0.1 // float flakeRoughness
    };
}