#ifndef SOLO_SHADER   
    #define ENTRY_WHEEL void 
#endif

#ifndef ENTRY_WHEEL
    #define  DEFAULT_WHEEL(x) = x
    #define ENTRY_WHEEL shader
#else
    #define  DEFAULT_WHEEL(x)
#endif

#include "MTX.h"
#include "Scratch.h"

ENTRY_WHEEL Wheel [[ 
    string nodegroup = "autolib", 
]] (

    vector UV  DEFAULT_WHEEL(vector(u, v, 0)),
    int useUV  DEFAULT_WHEEL(0) [[ string doc = "Defaults to P otherwise", string widget = "checkBox" ]],

    float scale  DEFAULT_WHEEL(1.0),

    float metallicDarkness  DEFAULT_WHEEL(0.95) [[ string uifolder = "Metallic", float uimin = 0.0, float uimax = 1.0 ]],
    float metallicRoughness  DEFAULT_WHEEL(1.0) [[ string uifolder = "Metallic", float uimin = 0.0, float uimax = 1.0 ]],

    output float hmmPattern  DEFAULT_WHEEL(0.0),
    output closure color Cout  DEFAULT_WHEEL(0)
) {

    point position = transform("object", useUV ? UV : P);

    vector fractalPattern = mx_fbm(
        position * scale, // position
        3, // octaves
        2.0, // lacunarity
        0.5, // diminish
        "snoise"
    );

    //worley patterns
    float worleyPattern = mx_worley_noise(
        fractalPattern, // p, 
        0.5, // jitter
        0, // style
        0 // metric
    );

    float worleyHeight = 0.005;
    point inverseWorleyBump = P + normalize(N) * (1.0 - (worleyPattern * worleyHeight)); //worley invered as bump map
    normal bumpedNormal = normalize(calculatenormal(inverseWorleyBump));


    //scratch pattern
    normal scratchNormal = normal(0, 0, 1);
     
    Scratch(
        vector(position),
        0.1, // density
        0.0, // roughnessMin
        0.3, // roughnessMax
        0.1, // roughnessDefault
        0.1, // anisotropicMin
        0.2, // anisotropicMax
        0.0, // anisotropicDefault
        0.001, // width
        0.0, // offset
        1.0, // normalStrength

        //output
        scratchNormal
    );

    closure color metalBase = conductor_bsdf(
        bumpedNormal, 0,
        metallicRoughness, // roughness_x 
        metallicRoughness, // roughness_y 
        1.4, // ior 
        color(metallicDarkness), // extinction 
        "ggx"
    );

    hmmPattern = worleyPattern;

    Cout = metalBase;
}