// AutolibAmbientOcclusion

shader AutolibAmbientOcclusion [[ 
    string category = "autolib" 
]] (
    color InputColor = 1,
    color HitColor = 0,
    closure color InputClosure = 0,
    closure color ClosureHit = 0,
    float AOAngle = 0.95,
    float MaxDistance = 25.0,
    vector BumpNormal = 0,
    output color Color = color(1, 0, 0),
    output closure color Closure = 0
) {
    int isRayTypeDiffuse = raytype("diffuse");
    
    if (isRayTypeDiffuse) {
        Color = InputColor;
        Closure = InputClosure;
    } else {
        // compute  vector to trace Ray = random * N
        vector bruitvector = vector ( 0.0 , 0.0 , 0.0 );
        vector VectorAO = N + BumpNormal + (0.001 * noise("perlin", P*10000.0 ));

        if ( AOAngle != 0.0 ){
            bruitvector = AOAngle * ( 1.0- 2.0 * noise("cell", VectorAO*10000.0 ) );
            VectorAO +=  bruitvector;
        }

        // trace Ray for AO
        float hitDistance = 1.0;
        float mixage = 1.0;
        vector DirTrace = normalize(VectorAO);
        
        int traceHit = trace(P, DirTrace, "maxdist" , MaxDistance );

        if (traceHit) {
            int hitTrace = getmessage("trace", "hitdist", hitDistance);

            mixage = clamp((hitDistance / MaxDistance), 0.0, 1.0);

            // make a gradient between the 2 colors to have smoother (and better quality) AO.
            Color = mix(HitColor, InputColor, mixage );
            Closure = (InputClosure * mixage)  + ClosureHit * (1.0 - mixage );
           
        } else {
            // else, return black
            Color = InputColor;
            Closure = InputClosure;
        }
    }
}
