/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

// AutolibImage

color colorUnpremultiply(color c, float alpha) {
    if (alpha != 1.0 && alpha != 0.0) {
        return c / alpha;
    }

    return c;
}

float valueUnpremultiply(float c, float alpha) {
    if (alpha != 1.0 && alpha != 0.0) {
        return c / alpha;
    }

    return c;
}

point texcoRemapSquare(point co) {
    return (co - point(0.5, 0.5, 0.5)) * 2.0;
}

point mapToTube(vector dir) {
    float u, v;
    v = (dir[2] + 1.0) * 0.5;
    float len = sqrt(dir[0] * dir[0] + dir[1] * dir[1]);
    if (len > 0.0) {
        u = (1.0 - (atan2(dir[0] / len, dir[1] / len) / M_PI)) * 0.5;
    } else {
        v = u = 0.0; // Avoid uninitialized variables.
    }
    return point(u, v, 0.0);
}

point mapToSphere(vector dir) {
    float len = length(dir);
    float v, u;
    if (len > 0.0) {
        if (dir[0] == 0.0 && dir[1] == 0.0) {
            u = 0.0; // Otherwise domain error.
        } else {
            u = (1.0 - atan2(dir[0], dir[1]) / M_PI) / 2.0;
        }
        v = 1.0 - acos(dir[2] / len) / M_PI;
    } else {
        v = u = 0.0; // Avoid uninitialized variables.
    }
    return point(u, v, 0.0);
}

void imageTextureLookup(
    string Filename,
    float u,
    float v,
    int compressAsSrgb,
    int ignoreAlpha,
    int unassociateAlpha,
    int singleChannel,
    int isFloat,
    string interpolation,
    string extension,
    output color rgb,
    output float value,
    output float alpha
) {

    if (singleChannel) {
        value = (float)texture(
            Filename, u, v, "wrap", extension, "interp", interpolation, "alpha", alpha
        );

        if (ignoreAlpha) {
            alpha = 1.0;
        } else if (unassociateAlpha) {
            value = valueUnpremultiply(value, alpha);

            if (!isFloat) {
                value = min(value, 1.0);
            }
        }


    } else {
        rgb = texture(
            Filename, u, v, "wrap", extension, "interp", interpolation, "alpha", alpha
        );

        if (ignoreAlpha) {
            alpha = 1.0;
        } else if (unassociateAlpha) {
            rgb = colorUnpremultiply(rgb, alpha);

            if (!isFloat) {
                rgb = min(rgb, 1.0);
            }
        }

        if (compressAsSrgb) {
            rgb = transformc("sRGB", "RGB", rgb);
        }
    }
}

shader AutolibImage [[
    string category = "autolib",
    string help = "Image texture lookup with optional projection mapping."
]] (
    point Vector = P [[ string label = "Vector", string help = "Input coordinate." ]],
    string Filename = "" [[ string path = "file" ]],
    string Projection = "flat" [[ string widget = "mapper", string options = "flat|box|sphere|tube" ]],
    string Interpolation = "smartcubic" [[ string widget = "mapper", string options = "smartcubic|cubic|linear|closest" ]],
    string Extension = "periodic" [[ string widget = "mapper", string options = "periodic|clamp|mirror|black|default" ]],
    float ProjectionBlend = 0.0 [[ float min = 0.0, float max = 1.0, int interactive = 1 ]],
    int CompressAsSrgb = 0 [[ string widget = "boolean", string label = "Convert sRGB" ]],
    int IgnoreAlpha = 0 [[ string widget = "boolean" ]],
    int UnassociateAlpha = 0 [[ string widget = "boolean" ]],
    int SingleChannel = 0 [[ string widget = "boolean", string help = "Output a single channel from the texture instead of a color." ]],
    int IsFloat = 1 [[ string widget = "boolean", string help = "Disable clamping for float textures." ]],
    int FlipV = 0 [[ string widget = "boolean", string help = "Flip the V coordinate" ]],

    output color Color = 0,
    output float Value = 0,
    output float Alpha = 1.0,
) {
    if (Filename == "" || !isconstant(Filename))
        return;

    int textureExists = 0;
    gettextureinfo(Filename, "exists", textureExists);
    if (!textureExists)
        return;

    point coord = Vector;

    if (FlipV) {
        coord[1] *= -1;
    }

    if (Projection == "flat") {
        imageTextureLookup(
            Filename,
            coord[0],
            coord[1],
            CompressAsSrgb,
            IgnoreAlpha,
            UnassociateAlpha,
            SingleChannel,
            IsFloat,
            Interpolation,
            Extension,
            Color,
            Value,
            Alpha
        );
    } else if (Projection == "box") {
        vector normalObject = transform("world", "object", N);

        vector signedNormalObject = normalObject;
        normalObject = vector(fabs(normalObject[0]), fabs(normalObject[1]), fabs(normalObject[2]));
        normalObject /= (normalObject[0] + normalObject[1] + normalObject[2]);

        vector weight = vector(0.0, 0.0, 0.0);
        float blend = ProjectionBlend;
        float limit = 0.5 * (1.0 + blend);

        if (normalObject[0] > limit * (normalObject[0] + normalObject[1]) &&
            normalObject[0] > limit * (normalObject[0] + normalObject[2])) {
            weight[0] = 1.0;
        } else if (normalObject[1] > limit * (normalObject[0] + normalObject[1]) &&
                   normalObject[1] > limit * (normalObject[1] + normalObject[2])) {
            weight[1] = 1.0;
        } else if (normalObject[2] > limit * (normalObject[0] + normalObject[2]) &&
                   normalObject[2] > limit * (normalObject[1] + normalObject[2])) {
            weight[2] = 1.0;
        } else if (blend > 0.0) {
            if (normalObject[2] < (1.0 - limit) * (normalObject[1] + normalObject[0])) {
                weight[0] = normalObject[0] / (normalObject[0] + normalObject[1]);
                weight[0] = clamp((weight[0] - 0.5 * (1.0 - blend)) / blend, 0.0, 1.0);
                weight[1] = 1.0 - weight[0];
            } else if (normalObject[0] < (1.0 - limit) * (normalObject[1] + normalObject[2])) {
                weight[1] = normalObject[1] / (normalObject[1] + normalObject[2]);
                weight[1] = clamp((weight[1] - 0.5 * (1.0 - blend)) / blend, 0.0, 1.0);
                weight[2] = 1.0 - weight[1];
            } else if (normalObject[1] < (1.0 - limit) * (normalObject[0] + normalObject[2])) {
                weight[0] = normalObject[0] / (normalObject[0] + normalObject[2]);
                weight[0] = clamp((weight[0] - 0.5 * (1.0 - blend)) / blend, 0.0, 1.0);
                weight[2] = 1.0 - weight[0];
            } else {
                weight[0] = ((2.0 - limit) * normalObject[0] + (limit - 1.0)) / (2.0 * limit - 1.0);
                weight[1] = ((2.0 - limit) * normalObject[1] + (limit - 1.0)) / (2.0 * limit - 1.0);
                weight[2] = ((2.0 - limit) * normalObject[2] + (limit - 1.0)) / (2.0 * limit - 1.0);
            }
        } else {
            weight[0] = 1.0;
        }

        Color = color(0.0);
        Value = 0.0;
        Alpha = 0.0;

        float tmpAlpha;
        color tmpColor;
        float tmpValue;
        

        if (weight[0] > 0.0) {
            point uv = point((signedNormalObject[0] < 0.0) ? 1.0 - coord[1] : coord[1], coord[2], 0.0);
            imageTextureLookup(
                Filename,
                uv[0],
                uv[1],
                CompressAsSrgb,
                IgnoreAlpha,
                UnassociateAlpha,
                SingleChannel,
                IsFloat,
                Interpolation,
                Extension,
                tmpColor,
                tmpValue,
                tmpAlpha
            );

            Alpha += weight[0] * tmpAlpha;
            Color += weight[0] * tmpColor;
            Value += weight[0] * tmpValue;
        }
        if (weight[1] > 0.0) {
            point uv = point((signedNormalObject[1] > 0.0) ? 1.0 - coord[0] : coord[0], coord[2], 0.0);
            imageTextureLookup(
                Filename,
                uv[0],
                uv[1],
                CompressAsSrgb,
                IgnoreAlpha,
                UnassociateAlpha,
                SingleChannel,
                IsFloat,
                Interpolation,
                Extension,
                tmpColor,
                tmpValue,
                tmpAlpha
            );
            Color += weight[1] * tmpColor;
            Value += weight[1] * tmpValue;
            Alpha += weight[1] * tmpAlpha;
        }
        if (weight[2] > 0.0) {
            point uv = point((signedNormalObject[2] > 0.0) ? 1.0 - coord[1] : coord[1], coord[0], 0.0);
            imageTextureLookup(
                Filename,
                uv[0],
                uv[1],
                CompressAsSrgb,
                IgnoreAlpha,
                UnassociateAlpha,
                SingleChannel,
                IsFloat,
                Interpolation,
                Extension,
                tmpColor,
                tmpValue,
                tmpAlpha
            );
            Color += weight[2] * tmpColor;
            Value += weight[2] * tmpValue;
            Alpha += weight[2] * tmpAlpha;
        }
    } else if (Projection == "sphere") {
        point projected = mapToSphere(texcoRemapSquare(coord));
        imageTextureLookup(
            Filename,
            projected[0],
            projected[1],
            CompressAsSrgb,
            IgnoreAlpha,
            UnassociateAlpha,
            SingleChannel,
            IsFloat,
            Interpolation,
            Extension,
            Color,
            Value,
            Alpha
        );
    } else if (Projection == "tube") {
        point projected = mapToTube(texcoRemapSquare(coord));
        imageTextureLookup(
            Filename,
            projected[0],
            projected[1],
            CompressAsSrgb,
            IgnoreAlpha,
            UnassociateAlpha,
            SingleChannel,
            IsFloat,
            Interpolation,
            Extension,
            Color,
            Value,
            Alpha
        );
    }
}
