// AutolibTestQuery

struct myvec {
    float x, y, z;
};

struct mystruct {
    float f;
    string s;
    int i;
    point p;
};

struct arraystruct {
    float farray[3];
    int iarray[2];
    //string sarray[3]; this causes a crash
};

shader AutolibTestQuery [[ 
    string category = "autolib" 
]] (
    // Test boring params
    float f = M_PI,
    string s = "hello",
    int i = 42,
    point p = point(1, 2, 3),
    color foo = color(0.25, 0.5, 0.75),
    color bar = color(0.75),
    matrix m = matrix(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),
    //myvec mv1 = { 0.25, 1.0, 2.0 },
    //myvec mv2 = { 0.25, 1.0, 2.0 },
    //mystruct ms = { 3.14, "world", 99, point(0,1,1) },
    //arraystruct as = { {1,2,3}, {2, 1} }, 
    output color out = 0,
    output closure color bsdf = 0,

    // Test array params

    int iarrayparam[1] = {1},
    int iarrayparamunsized[] = {7,8,9},

    float farrayparam[1] = {1},
    float farrayparamunsized[] = {7,8,9},

    color carrayparam[2] = {color(1,2,3), color(4,5,6)},
    color carrayparamunsized[] = {color(1,2,3), color(4,5,6), color(4,5,6), color(4,5,6), color(4,5,6)},

    vector varrayparam[3] = {vector(1,2,3), vector(4,5,6), vector(7,8,9)},
    vector varrayparamunsized[] = {vector(1,1,1), vector(2,2,2), vector(3,3,3), vector(3,2,1)},

    point parrayparam[2] = {point(1,2,3), point(4,5,6)},
    point parrayparamunsized[] = {point(1,2,3), point(4,5,6), point(4,5,6), point(4,5,6), point(4,5,6)},

    normal narrayparam[2] = {normal(1,2,3), normal(4,5,6)},
    normal narrayparamunsized[] = {normal(1,2,3), normal(4,5,6), normal(4,5,6), normal(4,5,6), normal(4,5,6)},

    output int iarrayparamout[2] = {1, 2},
    //output int iarrayparamunsizedout[] = {7,8,9}, no allowed
    output float farrayparamout[2] = {1, 2},
    output color carrayparamout[2] = {color(1,2,3), color(4,5,6)},
    output vector varrayparamout[2] = {vector(1,2,3), vector(4,5,6)},
    output point parrayparamout[2] = {point(1,2,3), point(4,5,6)},
    output normal narrayparamout[2] = {normal(1,2,3), normal(4,5,6)},

    // not allowed in osl
    //myvec sarrayparam[2] = { { 0.25, 1.0, 2.0 }, { 0.25, 1.0, 2.0 } },
    //myvec sarrayparamunsized[] = { { 0.25, 1.0, 2.0 }, { 0.25, 1.0, 2.0 }, { 0.25, 1.0, 2.0 } },

    //these have no analog in materialx
    //matrix marrayparam[2] = {matrix(1), matrix(4)},
    //matrix marrayparamunsized[] = {matrix(1), matrix(4), matrix(6), matrix(6), matrix(6)},

    // Test metadata retrieval
    int myparam1 = 1 [[ int i = 0, float f = 1.0, string s = "foo" ]],
    int myparam2 = 2 [[ string s[2] = { "foo", "bar" } ]],
    int myparam3 = 3 [[ float minmax[2] = { 42, 44 } ]],
    int myparam4 = 4 [[ color c = color(1,2,3) ]],
) {
    float localvariable = 0;  // should not be reported, of course
    printf ("foo=%f, bar=%f\n", foo, bar);
}