#define TRIANGLES 0
#define POLYGONS 1
#define PATCHES 2

shader AutolibWireframe [[ 
    string category = "autolib" 
]] (
    int EdgeType = POLYGONS [[ string widget = "mapper", string options = "triangles|polygons|patches" ]], 
    float LineWidth = 1  [[ float min = 0.0, int interactive = 1 ]], 
    int Raster = 1  [[ string widget = "boolean", int min = 0, int max = 1 ]],
    output float Value = 0
) {
    // ray differentials are so big in diffuse context that this function would always return "wire"
    if (raytype("path:diffuse")) {
        Value = 0.0;
        exit();
    }

    int np = 0;
    point p[64];
    float pixelWidth = 1;
    if (EdgeType == TRIANGLES) { // triangles
        np = 3;
        if (!getattribute("geom:trianglevertices", p)) {
            //Value = 0.0;
            exit();
        }
    } else if (EdgeType == POLYGONS || EdgeType == PATCHES) { // polygons or patches
        getattribute("geom:numpolyvertices", np);
        if (np < 3 || !getattribute("geom:polyvertices", p)) {
            //Value = 0.0;
            exit();
        }
    }

    if (Raster) {
        // Project the derivatives of P to the viewing plane defined
        // by I so we have a measure of how big is a pixel at this point
        float pixelWidthX = length(Dx(P) - dot(Dx(P), I) * I);
        float pixelWidthY = length(Dy(P) - dot(Dy(P), I) * I);
        // Take the average of both axis' length
        pixelWidth = (pixelWidthX + pixelWidthY) / 2;
    }

    // Use half the width as the neighbor face will render the
    // other half. And take the square for fast comparison
    pixelWidth *= 0.5 * LineWidth;
    pixelWidth *= pixelWidth;
    for (int i = 0; i < np; i++) {
        int i2 = i ? i - 1 : np - 1;
        vector dir = P - p[i];
        vector edge = p[i] - p[i2];
        vector crs = cross(edge, dir);
        // At this point dot(crs, crs) / dot(edge, edge) is
        // the square of area / length(edge) == square of the
        // distance to the edge.
        if (dot(crs, crs) < (dot(edge, edge) * pixelWidth)) {
            Value = 1;
            exit();
        }
    }
}
