#ifdef NO_ENTRY 
    #define ENTRY_TEST_QUERY void 
#endif

#ifndef ENTRY_TEST_QUERY
    #define  DEFAULT_TEST_QUERY(x) = x
    #define ENTRY_TEST_QUERY shader
#else
    #define  DEFAULT_TEST_QUERY(x)
#endif

struct myvec {
    float x, y, z;
};

ENTRY_TEST_QUERY TestQuery(
    // Test boring params
    float f = M_PI,
    string s = "hello",
    int i = 42,
    point p = point(1, 2, 3),
    color foo = color(0.25, 0.5, 0.75),
    color bar = color(0.75),
    matrix m = matrix(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),
    myvec mv1 = { 0.25, 1.0, 2.0 },
    myvec mv2 = { 0.25, 1.0, 2.0 },
    output color Cout = 0,
    output closure color bsdf = 0,

    // Test array params

    int iarrayparam[1] = {1},
    int iarrayparamunsized[] = {7,8,9},

    float farrayparam[1] = {1},
    float farrayparamunsized[] = {7,8,9},

    vector varrayparam[3] = {vector(1,2,3), vector(4,5,6), vector(7,8,9)},
    vector varrayparamunsized[] = {vector(1,1,1), vector(2,2,2), vector(3,3,3), vector(3,2,1)},

    point parrayparam[2] = {point(1,2,3), point(4,5,6)},
    point parrayparamunsized[] = {point(1,2,3), point(4,5,6), point(4,5,6), point(4,5,6), point(4,5,6)},

    normal narrayparam[2] = {normal(1,2,3), normal(4,5,6)},
    normal narrayparamunsized[] = {normal(1,2,3), normal(4,5,6), normal(4,5,6), normal(4,5,6), normal(4,5,6)},

    //these have no analog in materialx
    //matrix marrayparam[2] = {matrix(1), matrix(4)},
    //matrix marrayparamunsized[] = {matrix(1), matrix(4), matrix(6), matrix(6), matrix(6)},

    // Test metadata retrieval
    int myparam1 = 1 [[ int i = 0, float f = 1.0, string s = "foo" ]],
    int myparam2 = 2 [[ string s[2] = { "foo", "bar" } ]],
    int myparam3 = 3 [[ float minmax[2] = { 42, 44 } ]],
    int myparam4 = 4 [[ color c = color(1,2,3) ]],
    )
    [[ string author = "Jane Doe" ]]
{
    float localvariable = 0;  // should not be reported, of course
    printf ("foo=%f, bar=%f\n", foo, bar);
}