#ifndef SOLO_SHADER   
    #define ENTRY_SCRATCH void 
#endif 

#ifndef ENTRY_SCRATCH
    #define  DEFAULT_SCRATCH(x) = x
    #define ENTRY_SCRATCH shader
#else
    #define  DEFAULT_SCRATCH(x)
#endif

ENTRY_SCRATCH Scratch [[ 
    string nodegroup = "autolib", 
    int isdefaultversion = 1, 
    string version = "0.1" 
]] (
    vector UV  DEFAULT_SCRATCH(vector(u, v, 0)),
    float density  DEFAULT_SCRATCH(0.1),
    float width  DEFAULT_SCRATCH(0.001),
    float normalStrength DEFAULT_SCRATCH(1.0),
    output normal outNormal DEFAULT_SCRATCH(normal(0, 0, 1)),
    output float outAlpha DEFAULT_SCRATCH(0.0)
) {

    float delta = 1.0/(40 - 1);
    float maxRadius = sqrt(density);
    int maxSearchCell = (int)ceil(maxRadius/delta);
    point index = point(round(UV.x/delta), round(UV.y/delta), 0.0);

    int found = 0;
    for (int x = -maxSearchCell; x <= maxSearchCell && !found; ++x){
        for (int y = -maxSearchCell; y <= maxSearchCell && !found; ++y){
            point currentIndex = index + point(x, y, 0);
            point currentOrigin = (currentIndex + (hashnoise(currentIndex) - 0.5)) * delta;

            float directionValue = hashnoise(currentIndex + vector(123, 456, 0));
            
            float theta = directionValue * M_PI;

            vector bitangent = vector(-sin(theta), cos(theta), 0);
            
            vector diff = UV - currentOrigin;
            float dist = dot(diff, bitangent);
            float actualWidth = width * hashnoise(currentIndex);

            if (abs(dist) < actualWidth * 0.5) {
                float t = dist / (actualWidth * 0.5);

                outNormal = normalize(normal(0,0,1) - bitangent * t * normalStrength);
                outAlpha = 1.0;
                found = 1;
            }
        }
    }
}