
// retrieves name, hit point and normal of a probe ray
int probeForOutline( 
    vector rayDir, 
    point rayOrigin, 
    output string HitGeomName,
    output point HitPoint, 
    output normal HitNormal 
) {
    int hit = trace(rayOrigin, rayDir);   

    if (hit) {
        getmessage("trace","geom:name", HitGeomName);

        getmessage("trace", "P", HitPoint);
        HitPoint = transform("world", HitPoint);

        getmessage("trace", "N", HitNormal);
        HitNormal = normalize(transform("world", HitNormal));
    }

    return hit;

}

shader AutolibToonOutline [[ 
    string category = "autolib" 
]] (
    float width = 0.01 [[ string help = "Defines offset of the trace probe ray from the surface normal" ]],
    float DistanceThreshold = 1.1 [[ string help = "Defines a distance based comparison threshold for the probe and hit point" ]],
    float NormalThreshold = 0.1 [[ string help = "Defines a normal comparison threshold for the probe and hit point" ]],
    float NoiseScale = 0,
    float NoiseAmount = 0,
    output float Alpha = 0
) {

    for (int i = -1; i <= 1; i++) {
        float noisedWidth = width * noise("perlin", P * NoiseScale) * NoiseAmount;

        float eps = 1e-4;

        point rayOrigin1  = P + N * eps;
        point rayOrigin2 = P + N * (eps + width);

        vector rayDir = normalize(-I);

        string name1 = "nogeo";
        string name2;

        point hitPoint1;
        point hitPoint2;

        normal hitNormal1;
        normal hitNormal2;

        int hit1 = probeForOutline(rayDir, rayOrigin1, name1, hitPoint1, hitNormal1);
        if(!hit1) {
            Alpha = 1;
            break;
        }

        int hit2 = probeForOutline(rayDir, rayOrigin2, name2, hitPoint2, hitNormal2);
        if(!hit2) {
            Alpha = 1;
            break;
        }

        int meetsNameCriteria = (name1 != name2);
        int meetsDistanceCriteria = dot(hitPoint1, hitPoint2) < (1 - DistanceThreshold);
        int meetsNormalCriteria = dot(hitNormal1, hitNormal2) < (1.0 - NormalThreshold);

        //if the normals are different enough, or the distance is large enough, or the names are different enough, we have an outline
        if (meetsDistanceCriteria || meetsNormalCriteria || meetsNameCriteria) {
            Alpha = 1;
            break;
        }
    }
}